### DISCUSSION TITLE
Samsung heat pump

### DISCUSSION THREAD

**Discussion by brazoayeye** [omerfaruk-aran/esphome_samsung_hvac_bus#106] [Questions]
Hello, I'm trying to connect my esp to my samsung heat pump. It worked with a MIM-H04EN but I cannot connect it decently with HA so i tried with this component.

I bought [a cheap component](https://it.aliexpress.com/item/1005005866372508.html) and I connected it this way:
3.3V -> VCC
GPIO4 -> TX
GPIO34 -> RX
GND -> GND

A -> F1
B -> F2

the yaml i used:
```
esphome:
  name: samsung_ac
  friendly_name: espPdc

esp32:
  board: esp32dev
  framework:
    type: arduino
web_server:
  port: 80

# Enable logging
logger:
  level: INFO
  logs:
    component: ERROR # Remove the "Your component takes to long to respond warning"

# Enable native API for communication with Home Assistant, this can be removed if you do not plan to use it with Home Assistant
api:

# Enable OTA firmware update, you will be able to upload the firmware over WiFi without connecting the device by cables
ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "espPdc Fallback Hotspot"
    password: "espPdc123"

captive_portal:
    
# Specify pins used by the board to comunicate with RS485 board 
uart:
  tx_pin: GPIO4
  rx_pin: GPIO34
  # For older devices it could also be 2400. But you should start with 9600.
  baud_rate: 9600
  parity: EVEN

## SAMSUNG AC CONFIGURATION

# Import custom component from GitHub
external_components:
  - source: github://lanwin/esphome_samsung_ac@stable # use @main if you want the latest development (possibly unstable?)
    components: [samsung_ac]

# Configuration of AC component
samsung_ac:
  devices:
```

The log I had:
```
[20:57:19][W][samsung_ac:018]: update
[20:57:19][W][api.connection:102]: ESPHome Logs 2024.2.1 (192.168.32.251): Connection reset
[20:57:35][W][samsung_ac:673]: s:10.00.00 d:b0.00.ff NASA_OUTDOOR_CONTROL_WATTMETER_1UNIT  2380.000000
[20:57:35][W][samsung_ac:667]: s:10.00.00 d:b0.00.ff LVAR_OUT_CONTROL_WATTMETER_1W_1MIN_SUM 2471.000000
[20:57:35][W][samsung_ac:660]: s:10.00.00 d:b0.00.ff LVAR_OUT_CONTROL_WATTMETER_ALL_UNIT_ACCUM 1138.645000kwh
[20:57:39][W][samsung_ac:547]: s:20.00.00 d:b3.00.ff VAR_in_temp_room_f 20.000000
[20:57:39][W][samsung_ac:625]: s:20.00.00 d:b3.00.ff VAR_IN_TEMP_WATER_TANK_F 38.000000
[20:57:49][W][samsung_ac:018]: update
[20:58:18][W][samsung_ac:673]: s:10.00.00 d:b0.00.ff NASA_OUTDOOR_CONTROL_WATTMETER_1UNIT  2525.000000
[20:58:18][W][samsung_ac:667]: s:10.00.00 d:b0.00.ff LVAR_OUT_CONTROL_WATTMETER_1W_1MIN_SUM 2616.000000
[20:58:18][W][samsung_ac:660]: s:10.00.00 d:b0.00.ff LVAR_OUT_CONTROL_WATTMETER_ALL_UNIT_ACCUM 1138.688000kwh
[20:58:19][W][samsung_ac:018]: update
[20:58:20][W][samsung_ac:547]: s:20.00.00 d:b3.00.ff VAR_in_temp_room_f 20.000000
[20:58:20][W][samsung_ac:625]: s:20.00.00 d:b3.00.ff VAR_IN_TEMP_WATER_TANK_F 38.200000
[20:58:49][W][samsung_ac:018]: update
[20:59:00][W][samsung_ac:568]: s:20.00.00 d:b3.00.ff ENUM_in_operation_power on
[20:59:00][W][samsung_ac:574]: s:20.00.00 d:b3.00.ff ENUM_in_operation_mode 4
[20:59:00][W][samsung_ac:580]: s:20.00.00 d:b3.00.ff ENUM_in_fan_mode 3
[20:59:00][W][samsung_ac:602]: s:20.00.00 d:b3.00.ff ENUM_in_alt_mode 0
[20:59:00][W][samsung_ac:631]: s:20.00.00 d:b3.00.ff ENUM_IN_WATER_HEATER_POWER on
[20:59:00][W][samsung_ac:614]: s:20.00.00 d:b3.00.ff ENUM_in_louver_lr_swing 0
[20:59:01][W][samsung_ac:555]: s:20.00.00 d:b3.00.ff VAR_in_temp_target_f 30.000000
[20:59:01][W][samsung_ac:547]: s:20.00.00 d:b3.00.ff VAR_in_temp_room_f 20.000000
[20:59:01][W][samsung_ac:625]: s:20.00.00 d:b3.00.ff VAR_IN_TEMP_WATER_TANK_F 38.400000
[20:59:02][W][samsung_ac:673]: s:10.00.00 d:b0.00.ff NASA_OUTDOOR_CONTROL_WATTMETER_1UNIT  2600.000000
[20:59:02][W][samsung_ac:667]: s:10.00.00 d:b0.00.ff LVAR_OUT_CONTROL_WATTMETER_1W_1MIN_SUM 2691.000000
[20:59:02][W][samsung_ac:660]: s:10.00.00 d:b0.00.ff LVAR_OUT_CONTROL_WATTMETER_ALL_UNIT_ACCUM 1138.732000kwh
[20:59:19][W][samsung_ac:018]: update
[20:59:41][W][samsung_ac:547]: s:20.00.00 d:b3.00.ff VAR_in_temp_room_f 20.000000
[20:59:41][W][samsung_ac:625]: s:20.00.00 d:b3.00.ff VAR_IN_TEMP_WATER_TANK_F 38.600000
[20:59:46][W][samsung_ac:673]: s:10.00.00 d:b0.00.ff NASA_OUTDOOR_CONTROL_WATTMETER_1UNIT  2600.000000
[20:59:46][W][samsung_ac:667]: s:10.00.00 d:b0.00.ff LVAR_OUT_CONTROL_WATTMETER_1W_1MIN_SUM 2691.000000
[20:59:46][W][samsung_ac:660]: s:10.00.00 d:b0.00.ff LVAR_OUT_CONTROL_WATTMETER_ALL_UNIT_ACCUM 1138.732000kwh
[20:59:49][W][samsung_ac:018]: update
[21:00:19][W][samsung_ac:018]: update
[21:00:21][W][samsung_ac:547]: s:20.00.00 d:b3.00.ff VAR_in_temp_room_f 20.000000
[21:00:21][W][samsung_ac:625]: s:20.00.00 d:b3.00.ff VAR_IN_TEMP_WATER_TANK_F 38.800000
[21:00:29][W][samsung_ac:673]: s:10.00.00 d:b0.00.ff NASA_OUTDOOR_CONTROL_WATTMETER_1UNIT  2627.000000
[21:00:29][W][samsung_ac:667]: s:10.00.00 d:b0.00.ff LVAR_OUT_CONTROL_WATTMETER_1W_1MIN_SUM 2718.000000
[21:00:29][W][samsung_ac:660]: s:10.00.00 d:b0.00.ff LVAR_OUT_CONTROL_WATTMETER_ALL_UNIT_ACCUM 1138.777000kwh
[21:00:49][W][samsung_ac:018]: update
[21:01:02][W][samsung_ac:547]: s:20.00.00 d:b3.00.ff VAR_in_temp_room_f 20.000000
[21:01:02][W][samsung_ac:625]: s:20.00.00 d:b3.00.ff VAR_IN_TEMP_WATER_TANK_F 39.000000
[21:01:12][W][samsung_ac:673]: s:10.00.00 d:b0.00.ff NASA_OUTDOOR_CONTROL_WATTMETER_1UNIT  2667.000000
[21:01:12][W][samsung_ac:667]: s:10.00.00 d:b0.00.ff LVAR_OUT_CONTROL_WATTMETER_1W_1MIN_SUM 2758.000000
[21:01:12][W][samsung_ac:660]: s:10.00.00 d:b0.00.ff LVAR_OUT_CONTROL_WATTMETER_ALL_UNIT_ACCUM 1138.822000kwh
[21:01:19][W][samsung_ac:018]: update
```

I don't have the message with discovered devices, but it seems that the internal unit has address 20.00.00 and external 10.00.00.
I tried to add the internal device, but it can't compile with water_temperature or other options. 

What should I add? 
Is there a documentations that explains how to set capabilities section and devices one?

Thanks

**Comment by lanwin** [comment]
Can you please replace the logging sections with this:

```
logger:
  level: VERBOSE
  logs:
    component: ERROR
    climate: ERROR
    sensor: ERROR
    switch: ERROR
    json: DEBUG
```

Seems to be a bug in the logging config.

**Reply by brazoayeye** [reply]
Right, now i have
```
[12:30:35][C][samsung_ac:034]: Configured devices: 
[12:30:35][C][samsung_ac:054]: Discovered devices:
[12:30:35][C][samsung_ac:055]:   Outdoor: 10.00.00
[12:30:35][C][samsung_ac:056]:   Indoor:  20.00.00
```

How to proceed?
Adding 
```
  devices:
    - address: "20.00.00"
      water_temperature:
        name: "Warm water"

```
I have

```
samsung_ac: [source /config/esphome/samsungac.yaml:73]
  devices: 
    - address: 20.00.00
      
      [water_temperature] is an invalid option for [0]. Did you mean [target_temperature], [room_temperature]?
      water_temperature: 
        name: Warm water
```

**Comment by lanwin** [comment]
You need to switch to main branch for this to work. Its currently not available in stable.

`  - source: github://lanwin/esphome_samsung_ac@main`

**Reply by brazoayeye** [reply]
Right, now I can read the boiler temperature but I can't read heating temperature and to set both target. 
I read many discussions and it seems a well known lack, but idk the root cause of the problem.
Even if i programmed in C++ I'm a neophyte regarding esphome, so I probably can't help in a short time. After all many features are already implemented and protocols works so I suppose it's only a matter of mapping (am I wrong?)

Since I have a MIM-H04EN and a working IN-OUT device i could try to understand the message number for read and set parameters, or is there something I'm missing?

Idk where settings are stored (internal or external units), but for sure I should intercept it when sending from the WIFI module.
OFC it would be helpful if there was a print (maybe debug to be enabled in the yaml?) for all messages in the network.

PS: when i change the heating setpoint I read the message
`Request #Packet Src:62.00.56 Dst:20.00.00 {PacketInformation: 1;ProtocolVersion: 2;RetryCount: 0;PacketType: 1;DataType: 3;PacketNumber: 113} > Variable 4247 = 270`
where 270 means 27.0°C

when I start the heating i read
`Request #Packet Src:62.00.56 Dst:20.00.00 {PacketInformation: 1;ProtocolVersion: 2;RetryCount: 0;PacketType: 1;DataType: 3;PacketNumber: 153} > Enum 4000 = 1`
and 0 if i switch it off

when I change the DHW setpoint I have:
`Request #Packet Src:62.00.56 Dst:20.00.00 {PacketInformation: 1;ProtocolVersion: 2;RetryCount: 0;PacketType: 1;DataType: 3;PacketNumber: 163}  > Variable 4235 = 420`
Where 420 means 42.0

when I turn on the DHW i read:
`Request #Packet Src:62.00.56 Dst:20.00.00 {PacketInformation: 1;ProtocolVersion: 2;RetryCount: 0;PacketType: 1;DataType: 3;PacketNumber: 177} > Enum 4065 = 1`

**Reply by lanwin** [reply]
Sorry I overlooked you message. 

I am nut exactly sure what you mean. But yes all messages the Wifi module sends is logged in ESPHome. This can be used to create commands. 

@Mongey has an open pullrequest https://github.com/lanwin/esphome_samsung_ac/pull/95 where the code to set the water temp is missing. Maybe you could help him.

**Comment by brazoayeye** [comment]
I added a new feature in a fork regarding a parametrizable climate that should give more flexibility than previous one. 

I made few tests but seems running well, with my setup.

I added something in the example.yaml for the usage. 
In the yaml can be set 3 to 4 addresses for the climate, and other translations to match ClimateMode with the nasa information.

**Reply by lanwin** [reply]
Nice, can you create a pullreuqest (maybe draft) to discuss your changes?

**Reply by brazoayeye** [reply]
Done. I just pulled another feature (always only done with nasa, that's the only one I can test)

Added in the readme the how to use: it's to easen a lookup in the logged debug when directly checking app (official)/display values
```
 # Prints parsed read value only if it match the source address (optional) AND if it's exactly the number set on HA user interface
  debug_number:
    - name: "debugFrom10"
      source: "10.00.00"
```

**Comment by Mocky158** [comment]
Hello, I would like to ask if the setting of the specific temperature of the service water at the heat pump was somehow successful.
I also had this question before see: 
https://github.com/lanwin/esphome_samsung_ac/discussions/63

The sunny days are coming and I would like to use my PV to the maximum.

Thank you

**Reply by brazoayeye** [reply]
I can set both water temperature (heating) and dhw. 

Look at my repo at https://github.com/brazoayeye/esphome_samsung_ac , i made a pull request with my modifications. 
Look at the example.yaml , there you can find my working setup with addresses. Setup has been let voluntarily parameterizable to keep it customizable since IDK if all heat pumps uses the same nasa address.

**Reply by Mocky158** [reply]
I added the water temperature but I can only see the temperature. I would need to be able to change this value. Depending on the surplus of electricity from PV. Am I able to do this somehow?

**Reply by brazoayeye** [reply]
Try to switch to my repo, then add custom climate with same addresses as in example.yaml.

Then check if read values are right from ha

**Reply by Mocky158** [reply]
I'm sorry, but I don't know how to choose stable or action build?

That's changing here, isn't it?
external_components:
   - source: github://lanwin/esphome_samsung_ac@main
     components: [samsung_ac]

**Reply by brazoayeye** [reply]
Yes, just replace github://lanwin/esphome_samsung_ac@main with github://brazoayeye/esphome_samsung_ac@main

Here my setup
 ```
devices:
    - address: "20.00.00" #internal
      custom_climate:
        - name: "Water heater"
          status_addr: 0x4237 # mandatory address regarding status temperature
          set_addr: 0x4235    # mandatory address regarding setpoint temperature
          set_min: 40         # optional, default = 25°C
          set_max: 55         # optional, default = 65°C
          enable_addr: 0x4065 # mandatory enabling address, only 1/0 should be written there. Look at mode sub section
                              # By default the value is set = 1 when HA send a value > 0.

        - name: "Heating" # and also cooling
          status_addr: 0x4238
          set_addr: 0x4247
          set_min: 8          # large enough to let both ranges for heating (25-65)°C and cooling (8-25)°C
          set_max: 65
          enable_addr: 0x4000
          mode:
            addr: 0x4001     
            ClimateMode2Value: 1 # Default -1. Setting =1 the value CLIMATE_MODE_COOL==2 is translated as 1 into mode->addr
            ClimateMode3Value: 4 # Default -1. Setting = 4 the value CLIMATE_MODE_HEAT==3 is translated as 4 into mode->addr
            ClimateMode6Value: 0 # Default -1. Setting = 4 the value CLIMATE_MODE_AUTO==6 is translated as 0 into mode->addr
      energy_produced:
        name: "Produced energy"

        
    - address: "10.00.00" # external unit
      power_consumption:
        name: "Power consumption" #w
      energy_consumption:
        name: "Energy consumption" #kwh
      outdoor_temperature:
        name: "Outdoor temperature"
```

verbose setup for heating->mode->ClimateModeXValue are to let you choose from HA if the heatpump must heat, or cool the water. You can skip the entire mode: block if you want to set it manually from local display

**Reply by Mocky158** [reply]
I broke it up.
I would like to ask, can I add my own sensor? I would use the address from this list: https://wiki.myehs.eu/wiki/NASA_Protocol

I don't know if it's my fault, but I can't set the domestic water temperature to more than 50 degrees, so I don't know if it's possible for someone else to reset it to 55.

If so, do entities with consumption work for you? (w,kwh)

In case I could use the address 0x4066 ENUM_IN_WATER_HEATER_MODE
that I would force the pump to start heating right away in the tank even though there is still little hysteresis.

Or I couldn't find a sensor for setting the hysteresis anywhere, so I see that the hysteresis is 5 degrees.

EDIT: Now I found the entity 0x4252 which could limit the setting of the max temperature of service water.

**Reply by brazoayeye** [reply]
I can set the temperature up to 55°C, So I set this way my configuration. You can change set_max to modify climate min / max settable values. 

Consumptions and energy works, but sent from outside unit (not inside).
Inside unit send the produced energy

I checked all messages flowing in the network, so I added what worked in my case. I think it's easier to analyze message in the network before adding them on the code. 

You can set
`debug_log_messages: true` (see readme) to be able to see all messages in the terminal. Or let it run for 20 minutes in a terminal, then download and/or use search to find if mentioned addresses appears

Only with my repo you can set
```
  debug_number:
    - name: "myDebugInfo"
```
after installing you will find a settable number in HASS. The esp device analyze the data in the netowrk and print informations only regarding messages that have the same VALUE as set in HASS.
Since (in my case, idk if it's the same for you) temperature are sent as x/10, if you read on the display a temperature of 25.2° you have to set 252 in HASS to capture the packet address.
Ofc you must keep your eyes on terminal because informations are always printed there. 

Once found informations, you can set them

- Directly in the yaml for custom_climate
- In the `__init__.py` for custom sensors, since they are mapped from yaml name (example water_temperature ) to the address [there](https://github.com/brazoayeye/esphome_samsung_ac/blob/1c6970dde485a6d448b17d2faf3a99fe8e8f8fd3/components/samsung_ac/__init__.py#L229)

**Reply by Mocky158** [reply]
I have added debugging and am attaching the log.
I also found the value in the register 0x4252, which should correspond to the maximum temperature of service water, and it is really 500, which should correspond to 50 degrees. So do you have 550 for this register? that you can set up to 55 degrees?
![log](https://github.com/lanwin/esphome_samsung_ac/assets/90219705/d8fab435-54f5-436a-b6a7-27579efe7706)

Another question is how I could move this value to 550

[logs_m5-atomic-kotelna_logs (1).txt](https://github.com/lanwin/esphome_samsung_ac/files/14789122/logs_m5-atomic-kotelna_logs.1.txt)

**Reply by brazoayeye** [reply]
Yes sir, `> Variable 4252 = 550`
I started looking on local display to set limits, idk they were also readable using the serial. 

On the other side, i think it's not a good idea to change that value, probably it's something related to the device capability (maybe related to the gas type, or the compressor type). You can simply change the HASS climate with `set_max: 50`
If you want to force that value i suggest to do that way: recompile with a custom climate with set_addr: 0x4252 , then change as you change to set the temperature, then recompile with correct address 0x4235.

From log i see
0x4237 => 47.5°C (475)
0x4235 => 50.0 °C (set point)
0x4065 => 1 (enable heater)

With this configuration do you have problems?
I found a problem in my code when mode section was absent, i fixed it so now it's ok on git but idk how often your local cache is updated. Keep mode section to be sure

```
      custom_climate:
        - name: "Water heater"
          status_addr: 0x4237 # mandatory address regarding status temperature
          set_addr: 0x4235    # mandatory address regarding setpoint temperature
          set_min: 40         # optional, default = 25°C
          set_max: 55         # optional, default = 65°C
          enable_addr: 0x4065 
          mode:
            ClimateMode0Value: 0
            ClimateMode3Value: 1
```

I also found heating parameters:
 > Variable 4238 = 273 (heating currently 27.3°C)
> Variable 4247 = 450 (heating set point 45°C)
 > Enum 4000 = 1 (heating switched on)
 > Enum 4001 = 0 (heating in auto mode)

With this settings do you have problems? 
```
        - name: "Heating"
          status_addr: 0x4238
          set_addr: 0x4247
          set_min: 8          # large enough to let both ranges for heating (25-65)°C and cooling (8-25)°C
          set_max: 65
          enable_addr: 0x4000
          mode:
            addr: 0x4001    
            ClimateMode2Value: 1 # Default -1. Setting =1 the value CLIMATE_MODE_COOL==2 is translated as 1 into mode->addr
            ClimateMode3Value: 4 # Default -1. Setting = 4 the value CLIMATE_MODE_HEAT==3 is translated as 4 into mode->addr
            ClimateMode6Value: 0 # Default -1. Setting = 4 the value CLIMATE_MODE_AUTO==6 is translated as 0 into mode->addr
```

I can set from locale and HASS the heating in
OFF (Hass value = 0) ( NASA values 0x4000 = 0 )
AUTO (Hass value = 6) ( NASA values  0x4000 = 1,  0x4001 = 0)
HEAT (Hass value = 3) (  NASA values  0x4000 = 1,  0x4001 = 4)
COOL  (Hass value = 2) ( NASA values  0x4000 = 1,  0x4001 = 1)

If you have problems please provide yaml configuration, the problem and a serial log. After the upload wait a minute to have updated values before interacting

**Reply by Mocky158** [reply]
Thank you very much
I succeeded, now I can set up to 55
I know that the technician during the installation set me up, he said that the technology and gas can handle more, but that it will only heat up more often and that it is more efficient to heat due to less losses.
For me, it is about the fact that I know that the heat pump will not be as efficient at this value, but it will still be more efficient than the heating coil. When it's more than 20 degrees outside in the summer.


As for the configuration, I don't even have set values for the hot water in the floor unit, I don't want to interfere with that, it's controlled by the outdoor sensor and that suits me.

Otherwise, changing the water temperature worked well for me even without this setting.

           modes:
             ClimateMode0Value: 0
             ClimateMode3Value

**Reply by brazoayeye** [reply]
modes was needed to make usable the button OFF / HEAT in the bottom of the control. In the bugged version there were only Heat
![image](https://github.com/lanwin/esphome_samsung_ac/assets/33332672/ed0ce6c7-609d-4233-8bae-bf9a4b6cf618)

**Reply by Mocky158** [reply]
I see that even though the value has changed, it still doesn't work. The current temperature is 47, I set it to 55, but the water still did not start to heat up. I have been waiting for a long time.

**Reply by brazoayeye** [reply]
Very strange, please check in local screen if the settable range is still 50 or moved to 55. 
When you set the temperature, is the local screen showing the value accortingly?

I suppose that there is another limitation or paramter that limit the working range.
Check if there is a manual and a tech menu for the internal unit, maybe you can find a solution there to fix your problem

**Reply by brazoayeye** [reply]
For example for my controller the password is up and down for 3 sec and then 0202
![image](https://github.com/lanwin/esphome_samsung_ac/assets/33332672/228c2581-8d8c-44d8-946c-2781117ee7b6)

https://www.samsung.com/uk/support/model/MWR-WW10N/#downloads

**Reply by Mocky158** [reply]
Unfortunately, I only have hot water marked with dots.
![Snímek obrazovky 2024-04-02 v 7 06 35](https://github.com/lanwin/esphome_samsung_ac/assets/90219705/d72c64aa-5fd4-4923-be4b-e15fccc7ee11)

**Comment by Mocky158** [comment]
So the only place where I still have the value of 450 and it is hot water is the register (4247), it always returns to the value of 450 and it is not possible to set even a lower value.

If I wanted to try switching the mode to force (4066) I could use it like this?


     custom_climate:
       - name: "Water heater"
         status_addr: 0x4237 # mandatory address regarding status temperature
         set_addr: 0x4235   # mandatory address regarding setpoint temperature
         set_min: 40         # optional, default = 25°C
         set_max: 60         # optional, default = 65°C
         enable_addr: 0x4066 # mandatory enabling address, only 1/0 should be written there. Look at mode sub section
         mode:
          ClimateMode0Value: 0
          ClimateMode3Value: 1
          ClimateMode6Value: 2
          ClimateMode9Value: 3


[logs_m5-atomic-kotelna_run (16).txt](https://github.com/lanwin/esphome_samsung_ac/files/14851205/logs_m5-atomic-kotelna_run.16.txt)

**Reply by brazoayeye** [reply]
No, enable_addr is an address that's written =0 if you select 0 on HASS, 1 otherwise.
In my heat pump there are no modes for DHW, modes are intended in HASS as described [here](https://www.esphome.io/api/namespaceesphome_1_1climate#a8716cd7ed01ceb7ccedfa2f7b47a39d2)

For heating I can set what i [previous described](https://github.com/lanwin/esphome_samsung_ac/discussions/106#discussioncomment-8940119) : OFF, HEAT, COOL, AUTO
For DHW I can only set different [presets](https://www.esphome.io/api/namespaceesphome_1_1climate#a433110c27d12c36f0744c4c3827dd47e), but i haven't implemented them.

If you set only enable_addr you should see only OFF / HEAT in HASS: they are translated directly only in that address
If you set enable_addr and also mode->addr the mapping ClimateModexValue are written on mode->addr while enable_addr is 1 when climateMode is > 0

If you set it this way(note addresses 0x4065 and 0x4066
```
 custom_climate:
   - name: "Water heater"
     status_addr: 0x4237 # mandatory address regarding status temperature
     set_addr: 0x4235   # mandatory address regarding setpoint temperature
     set_min: 40         # optional, default = 25°C
     set_max: 60         # optional, default = 65°C
     enable_addr: 0x4065 # mandatory enabling address, only 1/0 should be written there. Look at mode sub section
     mode:
      addr: 0x4066
      ClimateMode0Value: 0
      ClimateMode3Value: 1
      ClimateMode6Value: 2
      #ClimateMode9Value: 3
```
the setup is translated this way:

ClimateMode0Value: 0 => when you click OFF  0x4065 = 0
ClimateMode3Value: 1 => when you click HEAT 0x4065 = 1, 0x4066 = 1
ClimateMode6Value: 2 => when you click AUTO 0x4065 = 1, 0x4066 = 2

Climate mode 9 doesn't even exists. 
You can try adding 
ClimateMode4Value: 3 => when you click FAN_ONLY0x4065 = 1, 0x4066 = 3

Names are nonsense, but at least you can set and test what you need. 
If it works, I can update the code to support ClimatePresets

**Reply by brazoayeye** [reply]
I pushed an update with the feature you need (always on https://github.com/brazoayeye/esphome_samsung_ac) 

All is described on example.yaml.
Try with this code (I don't remember how, but you have to refresh the git local cache of your HASS)

```
  custom_climate:
    - name: "Water heater"
      status_addr: 0x4237 # mandatory address regarding status temperature
      set_addr: 0x4235   # mandatory address regarding setpoint temperature
      set_min: 40         # optional, default = 25°C
      set_max: 60         # optional, default = 65°C
      enable_addr: 0x4065 # mandatory enabling address, only 1/0 should be written there. Look at mode sub section
      preset:         
        addr: 0x4066      # Address for presets
        ClimatePreset0Value: 1 # CLIMATE_PRESET_NONE => 1 Standard
        ClimatePreset1Value: -1 # CLIMATE_PRESET_HOME 
        ClimatePreset2Value: -1 # CLIMATE_PRESET_AWAY 
        ClimatePreset3Value: 2 # CLIMATE_PRESET_BOOST => 2 Power
        ClimatePreset4Value: -1 # CLIMATE_PRESET_COMFORT 
        ClimatePreset5Value: 0 # CLIMATE_PRESET_ECO => 0 Eco
        ClimatePreset6Value: -1 # CLIMATE_PRESET_SLEEP 
        ClimatePreset7Value: 3 # CLIMATE_PRESET_ACTIVITY  => 3 Force
```

It's not perfect because the value "Force" is not present in HASS enum. I saw it's possible to set a custom preset, but I don't have time to implement it now. Just use ACTIVITY preset (or others) instead of Force

Regards

**Reply by Mocky158** [reply]
Yes, it works.
Even yesterday I was able to switch it and there is even a timer that will return from the boost to the rated power. I think that is the designated time in the register(4266)
But they don't need to solve that.
This helped me tremendously, even though the water is 42, I was able to heat it to 45 immediately after switching. Not like before that it was waiting for it to cool down to a temperature of 38.
It would be even better if I could heat the water to more than 50C, but even then it will work :-)


As a result, I am already very satisfied.
Thank you very much for your help.

PS: I don't care if the names of the entities are different from what they actually are (active, none.etc), I'll set it up in automation once and then I won't have to deal with it anymore :-)

**Reply by brazoayeye** [reply]
I'm now trying to increase the maximum temperature of the DHW without success.
Basic config is maximum 55°C, If i set 65°C from hass it was reverted to 55°C.

I changed 
0x4252 | VAR_IN_FSV_1051 | NASA_DHW_MAX_SETTEMPLIMIT | User limitation - Hot Water Temperature Max.
to 650 (65°C) and now I can set 65 from local screen (and from hass) but boiler still stops at 55°C. I'm using eco mode, i really don't know what presets Eco-Standard-Power-Force means but i want to heat using heat pump not using the resistor

**Reply by Foxhill67** [reply]
May be try 0x4235 (VAR_IN_TEMP_WATER_HEATER_TARGET_F) instead of 0x4252?

**Reply by brazoayeye** [reply]
> 0x4235 (VAR_IN_TEMP_WATER_HEATER_TARGET_F)
0x4235 is the real setpoint, what is moved by local display or app to command the heat pump
That limit is limited at 55°C by default, and I can't find a way to increase that limit

**Reply by north3221** [reply]
@brazoayeye how are you setting 0x4252 using this? Is there a service call or something, I couldn't figure out how to change custom sensors?

As for your limit on 55°C, eco mode means it will only use heat pump (not immersion) and heat pump is limited to 55°C hot water. So if you want to go past that you need to set any of the other presets, standard will kick the immersion in after 20 mins.

**Reply by north3221** [reply]
@lanwin Appreciate the work on this and also how busy you are. I'm happy to help, have a samsung heat pump and, not an amazing dev, but I can prob help with some mappings of codes/settings etc. I've managed to map out some of the key stuff I need in custom sensors, now need to be able to control some.

I saw you are thinking of breaking down the components/project. I'll keep an eye on that.

In the meantime, Is there a guide somewhere to which parts of code need to be changed? I assume, need to create a const, a method for reading, and one for writing, and we ned to follow some standards. If not I'll look through other PRs to get an idea, would just be useful if there is a guide to help accelerate

**Reply by brazoayeye** [reply]
> how are you setting 0x4252 using this? Is there a service call or something, I couldn't figure out how to change custom sensors?

I made an improper use of custom climate (Implemented on one of the PR, https://github.com/brazoayeye/esphome_samsung_ac ). For example setting from
```
      custom_climate:
        - name: "Water heater"
          status_addr: 0x4237 # mandatory address regarding status temperature
          set_addr: 0x4252 
          set_min: 40         # optional, default = 25°C
          set_max: 65         # optional, default = 65°C
          enable_addr: 0x4065 # mandatory enabling address, only 1/0 should be written there. Look at mode sub section
                              # By default the value is set = 1 when HA send a value > 0.
```
I uploaded the new firmware and set the temperature of the climate to 65°C. Since esp think the set temperature should be written to set_addr: 0x4252 it will be written there. 
Ofc after I must revert to the original address (and to upload, etc) to use it and to check if it works differently. 

alternately you can create a different custom climate but since status_addr and enable_addr are mandatory i haven't tested it with the values as the other climate. 

I haven't fully understood what I should try to do to heat the hot water up to 65°C (as the pump can do, since it can be set for heating). From previous tests (and I should test more in the local device, since i tested mostly from hass) even if 0x4252 can change setting range for local display, the heat pump always stops at 55°C with all presets. I'll test more, hoping I'm wrong
