### DISCUSSION TITLE
[NonNASA] Outdoor Temperature - Home Assistant Sensor Request

### DISCUSSION THREAD

**Discussion by Goaheadz** [omerfaruk-aran/esphome_samsung_hvac_bus#108] [Questions] [answered]
Since there is already a message containing the outdoor temperature, I think making this as a HA sensor, would be handy for automation's.
This is the message I get:

 [W] | [samsung_ac:493] | MSG: {src:c8;dst:00;cmd:c0;commandC0:{ou_operation_mode:88; ou_4way_valve:0; ou_hot_gas_bypass:0; ou_compressor:0; ou_ac_fan:0; ou_outdoor_temp[°C]:13; ou_discharge_temp[°C]:11; ou_condenser_mid_temp[°C]:12}}
 
 Let me know what can I do, to make this possible.
 
 Help needed :)
 
 Thx
 G

</body>
</html>

**Comment by Goaheadz** [comment]
Beside de temperature, there is also the voltage and amperage being draw by the outdoor machine.
Since power from all splitters are connected to the outdoor, we could also use this information as sensors for consuption log and display.

like adding a new power draw like aqs in picture:

![image](https://github.com/lanwin/esphome_samsung_ac/assets/13796554/4b994895-6756-4660-8177-9e4ba493a709)

**Reply by brazoayeye** [reply]
I added that for NASA protocol in my pull request. IDK how it can be implemented for non-nasa protocol

**Reply by Goaheadz** [reply]
IDK either, but if its possible to extract temperature from sensors in splitters, it should be straigth forward to do the same for sensor in the outdoor machine.

@lanwin may be the saviour :)

**Reply by lanwin** [reply]
Yes its my plan to add that too. But did not expect it soon. My desk is currently overflowing with other work.

**Comment by Goaheadz** [comment]
No news regarding this?

**Comment by Goaheadz** [comment]
pushing up

**Comment by omerfaruk-aran** [comment]
Hello @Goaheadz,

I appreciate your efforts and interest in enhancing the project. Since I recently took over the project maintenance, I’m eager to help but need a bit more clarity on the Non-NASA protocol as my experience with it is limited.

From what I understand, you’re looking to add sensors for outdoor temperature and possibly for voltage and current measurements to track energy consumption. Is that correct?

To assist you effectively, it would be very helpful if you could provide the following:

Your Current YAML Configuration: This will give me a clear picture of how your ESPHome setup is structured and how the integration is currently working.
Relevant Log Entries: Please share a few lines from your log that contain the message data for outdoor temperature, voltage, and current, so I can see the exact format and structure.
Current Sensor Data from Your ESP Device: Any screenshots or JSON outputs from your ESP device showing the current sensor values would be helpful.
With this information, I can better understand your requirements and work towards implementing a solution. Looking forward to collaborating with you on this!

Best regards,
Ömer Faruk ARAN

**Reply by tech2urdoor** [reply]
[logs_atom_logs.txt](https://github.com/user-attachments/files/17551995/logs_atom_logs.txt)
[atom_yaml.txt](https://github.com/user-attachments/files/17551996/atom_yaml.txt)
Hi Ömer,
First of all, thank you so much for putting in your time and effort to continue with this project. I have a non-NASA unit and will happily share my yaml and logs with you to help you set this up. Please see attached yaml and log. Please note that I did try to add the outdoor temperature but it comes up as unknown. I have minimal programming skills but I see all this information show in my logs so hopefully it wouldn't be too hard to implement. 

Regards,
Brad

**Reply by omerfaruk-aran** [reply]
Hi Brad,

Thank you for your patience and willingness to help improve this project! I’ve implemented the outdoor temperature sensor in a new branch. To test it, please update your YAML configuration to use the custom branch:
```yaml
external_components:
  - source: github://omerfaruk-aran/esphome_samsung_hvac_bus@add-outdoor-sensors
    components: [samsung_ac]
```
Next, add the sensor configuration as shown below:

```yaml
  devices:
    - address: "c8" # Outdoor device address
      outdoor_temperature: 
        name: "Outdoor temperature"
```

Please upload this updated configuration to your ESP device and monitor the logs to see if the outdoor temperature sensor is working as expected. Let me know if you encounter any issues or if there are other details you want to refine!

Best regards,
Ömer Faruk ARAN

**Reply by tech2urdoor** [reply]
Hi Ömer,

It's my pleasure! I'm happy to test it. I just tried installing the new code and it wouldn't install, here is the log
[logs_atom_run.txt](https://github.com/user-attachments/files/17554618/logs_atom_run.txt)

Thanks
Brad

**Reply by omerfaruk-aran** [reply]
Thanks for testing it out and letting me know! I reviewed the code and realized there was a mistake in the naming of one of the sensors. I’ve corrected it now, so the configuration and code should match up. Could you please give it another try and let me know if it works this time?

**Reply by tech2urdoor** [reply]
Still no luck. Here's the log again.

[logs_atom_run2.txt](https://github.com/user-attachments/files/17555971/logs_atom_run2.txt)

**Reply by omerfaruk-aran** [reply]
The error you encountered might be due to the ESPHome source not being updated. To fix this, try adding refresh: 0s to the external_components configuration, which forces ESPHome to pull the latest source every time. Here’s an example:

```yaml
external_components:
  - source: github://omerfaruk-aran/esphome_samsung_hvac_bus@add-outdoor-sensors 
    components: [samsung_ac]
    refresh: 0s
```
This will ensure that the latest code version is used, preventing errors caused by outdated cached versions.

**Reply by tech2urdoor** [reply]
That helped install the code but unfortunately, the sensor is unknown in Home Assistant. Yaml and Log attached. Thank you for taking the time to do this. I am off to bed for the night now. Can continue testing tomorrow.
[atom_yaml.txt](https://github.com/user-attachments/files/17556160/atom_yaml.txt)
[logs_atom_run3.txt](https://github.com/user-attachments/files/17556161/logs_atom_run3.txt)

**Reply by tech2urdoor** [reply]
![image](https://github.com/user-attachments/assets/185e18c1-0364-4941-b24e-0ab4b71f09b8)

**Reply by omerfaruk-aran** [reply]
Good night! We’ve made some improvements in the Samsung AC component related to processing the outdoor temperature. Could you please check it again and let us know if the issue is resolved?

**Comment by Jkirjo** [comment]
That outdoor unit reported outside temp would be nice addition in generally. Most likely it is also available in data stream. I'm also interested in, what unit reporting about defrost cycles. In winter time that could be worth of to know.

**Comment by tech2urdoor** [comment]
[logs_atom_logs.txt](https://github.com/user-attachments/files/17551984/logs_atom_logs.txt)
[atom_yaml.txt](https://github.com/user-attachments/files/17551985/atom_yaml.txt)

**Comment by Goaheadz** [comment]
Hi Aran,

Thank you so much for all the time you put into this.

As soon as I get home (later in the day) I will also provide some log files and yaml (currently the AC breaker is OFF), and try the new sensor.

  devices:
    - address: "c8" # Outdoor device address
      outdoor_temperature: 
        name: "Outdoor temperature"

Adding inverter_power[W] sensor, will also allow us, to create a Energy sensor in Home Assistant and control consumption and costs per outdoor unit.

**Comment by omerfaruk-aran** [comment]
Hi @Goaheadz, @tech2urdoor,

Thank you for the feedback. I have updated the setup and here's an example of how to update your `yaml` configuration:

1. Update the `external_components` section:

```yaml
external_components:
  - source: github://omerfaruk-aran/esphome_samsung_hvac_bus@add-outdoor-sensors 
    components: [samsung_ac]
    refresh: 0s

```

1. Add the new sensors to your devices:

```yaml
devices:
  - address: "c8" # Outdoor device address
    outdoor_temperature: 
      name: "Outdoor temperature"

    outdoor_instantaneous_power:
      name: "Outdoor Instantaneous Power"

    outdoor_cumulative_energy:
      name: "Outdoor Cumulative Energy"

    outdoor_current:
      name: "Outdoor Current"

    outdoor_voltage:
      name: "Outdoor Voltage"

```

After updating this configuration, please build and flash your ESP device. Let me know if you encounter any issues or need further assistance.
