### DISCUSSION TITLE
does this register contain COP or SCOP?

### DISCUSSION THREAD

**Discussion by Krzysiek1976** [omerfaruk-aran/esphome_samsung_hvac_bus#142] [Questions]
Hi
Will we be able to read these values ​​using the Custom sensor? Unfortunately, I am not a programmer or IT specialist, but I understand EspHome as a Home Assistant user. 
0x4426 | LVAR_IN_?? |   | Generated power last minute |  
-
0x4427 | LVAR_IN_?? |   | Total generated power

Krzysiek

**Comment by brazoayeye** [comment]
I have for **INTERNAL** unit (20.00.00)

```
      custom_sensor:
        - name: Produced energy
          message: 0x4427
          device_class: energy
          state_class: total_increasing
          unit_of_measurement: kWh
```

I don't know if it works with 0x4426, depends on the fact that the heat pump send that data over the network or not. You can try and give us a feedback regarding the device you have and what you tested. 

PS: check the correct state_class between options at https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes . Probably right is measurement because value is updated every minute without considering the value in the previous minute
