### DISCUSSION TITLE
[Question]  water_target_temperature component

### DISCUSSION THREAD

**Discussion by Beormund** [omerfaruk-aran/esphome_samsung_hvac_bus#233] [Questions]
### Your Question

Should the on_value event fire on this number component?

### Additional Context

If the water_target_temperature value is changed from the Home Assistant UI or the ESPHome Web UI on_value does not appear to fire. I'm trying to update the target temperature on my own climate control using this event but it does not fire.

```yaml
      water_target_temperature:
        name: "DHW Target Temperature"
        id: hot_water_target_temp
        on_value:
          then:
            - logger.log:
                level: INFO
                format: "x: %f; DHW Target Temp: %f"
                args: ['x', 'id(climate_hot_water).target_temperature']
            - if:
                condition:
                  lambda: "return x != id(climate_hot_water).target_temperature;"
                then:
                  - climate.control:
                      id: climate_hot_water
                      target_temperature: !lambda "return x;"
```

I did some testing with a Template Number component in ESPHome and found that if the optimistic: True variable was missing then on_value did not fire. Has optimistic: True been set on water_target_temperature?

```yaml
number:
  platform: "template"
  id: "test"
  min_value: 20
  max_value: 70
  optimistic: True
  set_action:
    then:
      - logger.log:
          level: INFO
          format: "set_cction value: %f"
          args: ['x']
  step: 1
  on_value:
    then:
      - logger.log:
          level: INFO
          format: "on_value value: %f"
          args: ['x']
```

### Pre-Submission Checklist

- [X] I have searched for a similar question in open/closed issues.
- [X] I have checked the project’s documentation for relevant information.
- [X] I have provided as much detail as possible to help answer my question.

### HVAC System Type

NASA (Bus Protocol)

### Samsung HVAC Device Model

AE120RXYDEG/EU

### ESP Device Model

lilygo t rss3 esp32 s3

### Connection Pins

F1/F2

### YAML Configuration

```yaml
samsung_ac: 

  debug_log_messages: true 

  devices:

    - address: "20.00.00" # Indoor Device

      # DHW
      water_heater_power:
        name: "DHW Power"
        id: dhw_power
        on_turn_off:
          then:
            - if:
                condition:
                  lambda: "return id(climate_hot_water).mode > 0;"
                then:
                  - climate.control:
                      id: climate_hot_water
                      mode: "OFF"
        on_turn_on:
          then:
            - if:
                condition:
                  lambda: "return id(climate_hot_water).mode != 3;"
                then:
                  - climate.control:
                      id: climate_hot_water
                      mode: "HEAT"

      water_temperature:
        name: "DHW Temperature"
        id: hot_water_current_temp
      water_heater_mode:
        name: "DHW Mode"
        id: hotwater_mode
      water_target_temperature:
        name: "DHW Target Temperature"
        id: hot_water_target_temp
        on_value:
          then:
            - logger.log:
                level: INFO
                format: "x: %f; DHW Target Temp ii: %f"
                args: ['x', 'id(climate_hot_water).target_temperature']
            - if:
                condition:
                  lambda: "return x != id(climate_hot_water).target_temperature;"
                then:
                  - climate.control:
                      id: climate_hot_water
                      target_temperature: !lambda "return x;"


      # Heating
      power:
        name: "Zone Power"
        id: zone_power
        on_turn_off:
          then:
            - if:
                condition:
                  lambda: "return id(climate_heating).mode > 0;"
                then:
                  - climate.control:
                      id: climate_heating
                      mode: "OFF"
        on_turn_on:
          then:
            - if:
                condition:
                  lambda: "return id(climate_heating).mode != 3;"
                then:
                  - climate.control:
                      id: climate_heating
                      mode: "HEAT"        
      room_temperature:
        name: "Zone Temperature"
        id: zone_current_temp
      mode:
        name: "Zone Mode"
      target_temperature:
        name: "Zone Target Temperature"
        id: zone_target_temp
        on_value:
          then:
            - climate.control:
                id: climate_heating
                target_temperature: !lambda "return x;"



      
    - address: "10.00.00" # Outdoor device
      

      # This sensor captures and monitors specific error codes returned by the HVAC system.
      # When an error occurs, the sensor detects the error code and updates its value accordingly.
      # Additionally, by using the blueprint available at https://github.com/omerfaruk-aran/esphome_samsung_ac_blueprint,
      # you can automatically send detailed error messages to your mobile devices based on the captured error codes.
      error_code:
        name: "Error Code"
        
      # This sensor measures the instantaneous power consumption of the outdoor unit in Watts.
      # The captured value represents the current power draw of the outdoor HVAC components, helping track energy usage patterns.
      outdoor_instantaneous_power:
        name: "Heat Pump Instantaneous Power"

      # This sensor records the cumulative energy consumption of the outdoor unit in kWh.
      # It calculates the total energy consumed over time, allowing users to monitor and analyze energy efficiency.
      outdoor_cumulative_energy:
        name: "Heat Pump Cumulative Energy"

      # This sensor measures the current drawn by the outdoor unit in Amperes.
      # Monitoring current values helps identify electrical irregularities and ensure safe power levels in the system.
      outdoor_current:
        name: "Heat Pump Current"

      # This sensor tracks the voltage supplied to the outdoor unit in Volts.
      # Consistent voltage readings indicate stable power delivery, while deviations can help detect electrical issues in the system.
      outdoor_voltage:
        name: "Heat Pump Voltage"

       
# Sensor with id hp_dhw_max_temp, this is the temp at which the heat pump is set to use the compressor to heat hot water. 
# When water is requested that is hotter than that (which I do overnight on cheap rate) it flicks it out of eco and into standard.       
sensor:
  - platform: template
    id: hp_dhw_max_temp
    lambda: |-
      return 40.0;
    update_interval: never


climate:

  # DHW Climate Control
  - platform: thermostat
    name: "Hot Water"
    id: climate_hot_water
    sensor: hot_water_current_temp
    min_heating_off_time: 300s
    min_heating_run_time: 300s    
    min_idle_time: 30s
    target_temperature_change_action:
      then:
        - logger.log:
            level: INFO
            format: "DHW Target Temp i: %f"
            args: ['id(climate_hot_water).target_temperature']
        - number.set:
            id: hot_water_target_temp
            value: !lambda "return id(climate_hot_water).target_temperature;"
    heat_action: {}
    idle_action: {}
    off_mode:
      then:
        - if:
            condition:
              switch.is_on: dhw_power
            then:
              switch.turn_off: dhw_power
    heat_mode:
      then:
        - if:
            condition:
              switch.is_off: dhw_power
            then:
              switch.turn_on: dhw_power
    default_preset: ECO
    preset:
      - name: ECO
        default_target_temperature_low: 40 °C
      - name: HOME
        default_target_temperature_low: 45 °C
      - name: AWAY
        default_target_temperature_low: 20 °C
      - name: BOOST
        default_target_temperature_low: 55 °C
      - name: SLEEP
        default_target_temperature_low: 70 °C
    visual:
      min_temperature: 20
      max_temperature: 70
      temperature_step:
        target_temperature: 0.5
        current_temperature: 0.1

  # Zone Climate Control
  - platform: thermostat
    name: "Heating"
    id: climate_heating
    sensor: zone_current_temp
    min_heating_off_time: 300s
    min_heating_run_time: 300s    
    min_idle_time: 30s    
    heat_action: {}
    idle_action: {}
    off_mode:
      then:
        - if:
            condition:
              switch.is_on: zone_power
            then:
              switch.turn_off: zone_power
    heat_mode:
      then:
        - if:
            condition:
              switch.is_off: zone_power
            then:
              switch.turn_on: zone_power 
    visual:
      min_temperature: 0
      max_temperature: 70
      temperature_step:
        target_temperature: 1
        current_temperature: 0.1
```
