### DISCUSSION TITLE
Idle / Heating Status

### DISCUSSION THREAD

**Discussion by Beormund** [omerfaruk-aran/esphome_samsung_hvac_bus#236] [Questions]
With my heat pump, there is independent on/off power control for DHW and heating. If the heating is ON, but room stats are at or above target temperature, then the heating is "idle." When the stats call for heat, then the heat pump fires up, and the underfloor heating and/or radiator valves open (lights on them turn on) along with various pumps. The same goes for DHW. It can be powered on but "idle" until the water tank stat calls for heat. 

So my question is: Are there NASA codes that indicate heating and/or hot water are "idle" or "heating" (which is independent of their power status)? I thought that since the heat pump controller switches on and off the various valves, there may be associated NASA messages? 

Right now, my ESPHome thermostat climate controls are correctly showing the mode ("off" or "heat") but not the  action ("idle" or "running").

Any ideas?

**Comment by brazoayeye** [comment]
It could be, you can sniff packets and forcing on-off using thermostat to understand the communication

**Reply by Beormund** [reply]
I figured it out:

```yaml
        # 0x4067: ENUM_IN_3WAY_VALVE
        # On control board the valve is connected to Pin B17
        # Pin B17 is a switched live output to the DHW Valve
        # 0 = Room; 1 = Tank (from NASA docs)
        # If Room then Action = Idle
        # If Tank then Action = Heating
        - id: hot_water_heating
          message: 0x4067
          state_class: measurement
          on_value:
            then:
              - if:
                  condition:
                    lambda: "return x == 0;"
                  then:
                    - binary_sensor.template.publish:
                        id: hot_water_running
                        state: OFF
                    - text_sensor.template.publish:
                        id: hot_water_action
                        state: "Idle"
                  else:
                    - binary_sensor.template.publish:
                        id: hot_water_running
                        state: ON
                    - text_sensor.template.publish:
                        id: hot_water_action
                        state: "Heating"

        # 0x4069: ENUM_IN_THERMOSTAT1
        # On control board the on/off thermostat is connected to Pin B22
        # Pin B22 is a command input (Command Signal Zone 1 Heating)
        # 0 = Off, 1 = Cool, 2 = Heat (from NASA docs)
        # If Off then Action = Idle
        # If Heat then Action = Heating
        - id: zone_heating
          message: 0x4069
          state_class: measurement
          on_value:
            then:
              - if:
                  condition:
                    lambda: "return x == 0;"
                  then:
                    - binary_sensor.template.publish:
                        id: heating_running
                        state: OFF
                    - text_sensor.template.publish:
                        id: heating_action
                        state: "Idle"
                  else:
                    - binary_sensor.template.publish:
                        id: heating_running
                        state: ON
                    - text_sensor.template.publish:
                        id: heating_action
                        state: "Heating"
```
And the result in Home Assistant:
<img width="972" alt="Screenshot 2024-12-12 at 23 45 45" src="https://github.com/user-attachments/assets/fd790caa-2c39-4c9e-8ccf-3b0d20c880fa" />
