### DISCUSSION TITLE
Water heating mode

### DISCUSSION THREAD

**Discussion by BertBJ40** [omerfaruk-aran/esphome_samsung_hvac_bus#245] [General]
Newbie here. Who can help me on my way? I can read all data perfectly, but now I would like to program the water heating mode. I want to switch between eco and standard mode. However, I cannot find an entity that displays this mode. In the dashboard, manual switching is possible. Who can help me?

**Comment by north3221** [comment]
hi - you want this in your yaml config file, from the examples/yaml:

```yaml
    water_heater_mode:
      name: "Hotwater Mode"
      id: hotwater_mode
```
