### DISCUSSION TITLE
"still" doesn't compile on ESP-IDF

### DISCUSSION THREAD

**Discussion by DerTiger1** [omerfaruk-aran/esphome_samsung_hvac_bus#246] [General]
@omerfaruk-aran, thank you for the fast response but you closed the thread as solved so I can't respones anymore.

The issue is still here:
![grafik](https://github.com/user-attachments/assets/5563ae96-a551-4f79-bcf1-54a3cea88360)

**Comment by omerfaruk-aran** [comment]
Hello, the topic has been closed because the problem has been resolved. It should have been resolved for you too. I think you have another problem. Can you send your yaml example?

**Reply by DerTiger1** [reply]
Gave it another try: Compiled successfull !!! => thx

Here is my yaml - nothing changed the last months:

```
substitutions:
  esp32_name: "esphome-klimaanlage"
  device_description: "M5-Atom Stack mit RS485 Interface"

esphome:
  name: ${esp32_name}
  comment: ${device_description}
  build_path: "../config/esphome/${esp32_name}"

external_components:
  - source: github://omerfaruk-aran/esphome_samsung_hvac_bus@main # Use @stable if you want a more stable experience, but note a lot of this example code breaks.
 # - source: github://lanwin/esphome_samsung_ac@main
 # - source: github://DerTiger1/esphome_samsung_ac@main
 # - source: github://Foxhill67/esphome_samsung_ac@main
    components: [samsung_ac]
 # - source: github://oxan/esphome-stream-server

esp32:
  board: m5stack-atom
  framework:
    # type: arduino
    type: esp-idf
    version: recommended

uart:
  id: RS485
  tx_pin: GPIO19
  rx_pin: GPIO22
  baud_rate: 9600
  parity: EVEN

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret ha_key
  reboot_timeout: 60s
  
ota:
  - platform: esphome
    password: !secret ota_key

safe_mode:
  num_attempts: 1


wifi:
  ssid: !secret iot_ssid
  password: !secret iot_password
  domain: .iot.local
  reboot_timeout: 5min
  manual_ip:
    static_ip: 192.168.2.222
    gateway: 192.168.2.8
    subnet: 255.255.255.0
  ap:
    ssid: "Klimaanlage Fallback Hotspot"
    password: !secret wifi_ap_password

#stream_server:
  
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

sensor:
  - platform: homeassistant
    id: TemperaturOG
    accuracy_decimals: 1
    entity_id: sensor.meter_og_temperature

  - platform: homeassistant
    id: TemperaturKlima
    accuracy_decimals: 1
    entity_id: sensor.klima_ist_temperatur

  - platform: homeassistant
    id: SollwertOG2
    accuracy_decimals: 1
    entity_id: input_number.heizung_sollwert_og2

# Home Assistant switches usw.
switch:
  - platform: safe_mode
    internal: true
    name: use_safe_mode

button:
  - platform: restart
    name: Restart $esp32_name

samsung_ac:
  debug_log_messages: false # logs all messages - only for debugging
  debug_log_messages_raw: false # logs the raw message bytes from all messages - only for debugging
  capabilities: 
    vertical_swing: true
    presets:
      quiet:
        enabled: true
      fast:
        enabled: true
      windfree:
        enabled: true
      sleep:
        enabled: true
  devices:
    - address: "20.00.00" # for non NASA it sould be like "c4"
      # Each property below are optional - choose what you want to use.

      # You could use the ESPHome/Homeassist climate control
      climate:
        name: "ESP32 mit RS485 Verbindung zur Klimaanlage"
        id: my_climate
        visual:
          min_temperature: 16 °C
          max_temperature: 26 °C
          temperature_step: 0.1 °C
      # And/or use seperate controls/sensors
      room_temperature:
        name: Klima_Ist_Temperatur
      target_temperature:
         name: Klima_Soll_Temperatur
      power:
        name: Klima_power
      mode:
        name: Klima_mode

      # Only supported on NASA devices
      room_humidity:
        name: Klima_Luftfeuchtigkeit
    - address: "10.00.00"
      outdoor_temperature: # Should be used with outdoor device address
        name: "Klima_Aussentemperatur"
      custom_sensor:
        - name: AC Spannung
          message: 0x24fc
          device_class: voltage
          state_class: measurement
          unit_of_measurement: V
        - name: AC Current
          message: 0x8217
          device_class: current
          state_class: measurement
          unit_of_measurement: A
          accuracy_decimals: 1
          filters:
            - multiply: 0.1
        - name: AC Leistung
          message: 0x8413
          device_class: power
          state_class: measurement
          unit_of_measurement: W
          filters:
            - multiply: 1.5
        - name: AC Energie
          message: 0x8414
          device_class: energy
          state_class: total_increasing
          unit_of_measurement: kWh
          accuracy_decimals: 1
          filters:
            - multiply: 0.001
        - name: Compressor Frequency
          message: 0x8238
          device_class: frequency
          state_class: measurement
          unit_of_measurement: Hz
          accuracy_decimals: 1
        - name: Target Compressor Frequency
          message: 0x8237
          device_class: frequency
          state_class: measurement
          unit_of_measurement: Hz
          accuracy_decimals: 1
        - name: Fan Speed
          message: 0x823D
          state_class: measurement
          unit_of_measurement: RPM
          accuracy_decimals: 1
        - name: Static pressure
          message: 0x4299
          device_class: pressure
          state_class: measurement
          unit_of_measurement: Pa
```

**Reply by omerfaruk-aran** [reply]
Hello @DerTiger1,
I couldn't see the following `debug_mqtt_...` definitions in your YAML example. Also, could you try adding `refresh: 0` to the `external_components` section to ensure the latest version is downloaded and try again?

```yaml
external_components:
  - source: github://omerfaruk-aran/esphome_samsung_hvac_bus@main
    components: [samsung_ac]
    refresh: 0s

samsung_ac:

  # Sends all NASA package values to MQTT so they can be analyzed or monitored.
  debug_mqtt_host: 192.168.1.100
  debug_mqtt_port: 1883
  debug_mqtt_username: mqtt_user
  debug_mqtt_password: mqtt_pass
```
