### DISCUSSION TITLE
[Question] Help with YAML config file

### DISCUSSION THREAD

**Discussion by llubi23** [omerfaruk-aran/esphome_samsung_hvac_bus#252] [Questions]
### Your Question

Downloaded the example YAML file, changed it and uploaded to the ESP device via USB. Connected to the AC and I can read everything, then edited the YAML again with the addresses and the compiler says problems in lines I didn't changed

### Additional Context

Compiler finding syntax errors in lines that are not modified

### Pre-Submission Checklist

- [X] I have searched for a similar question in open/closed issues.
- [X] I have checked the project’s documentation for relevant information.
- [X] I have provided as much detail as possible to help answer my question.

### HVAC System Type

NASA (Bus Protocol)

### ESP Device Model

M5STACK ATOM LITE + ATOM RS485

### Connection Pins

F1 + F2

### YAML Configuration

```yaml
# This example provides a basic configuration and description based on the M5STACK components
# For further configuration you should visit the ESPHome docs https://esphome.io
# Every line starting with a # can be removed.

## BASIC CONFIGURATION
esphome:
  name: samsung_ac1
  friendly_name: AC_Menjador

# Select chipset and board configuration - in this case M5STACK
esp32:
  board: m5stack-atom

# [Optional] - Create web interface where you can control the AC from your web browser (without Home Assistant)
web_server:
  port: 80

# Enable logging
logger:
  logs:
    component: ERROR # Remove the "Your component takes to long to respond warning"

# Enable native API for communication with Home Assistant, this can be removed if you do not plan to use it with Home Assistant
api:

# Enable OTA firmware update, you will be able to upload the firmware over WiFi without connecting the device by cables
ota:
  platform: esphome

# Setup your WiFi password
wifi:
  ssid: "AltUrgellFibra-04CBAC" # !!!CHANGE ME!!!
  password: "APwAC5FH" # !!!CHANGE ME!!!

captive_portal:

# Specify pins used by the board to comunicate with RS485 board - in this case M5STACK
uart:
  tx_pin: GPIO19   # Use GPIO26 for ATOM Tail485 
  rx_pin: GPIO22   # Use GPIO32 for ATOM Tail485
  # For older devices it could also be 2400. But you should start with 9600.
  baud_rate: 9600
  parity: EVEN

## SAMSUNG AC CONFIGURATION

# Import custom component from GitHub
external_components:
  - source: github://omerfaruk-aran/esphome_samsung_hvac_bus@main # Use @stable if you want a more stable experience, but note a lot of this example code breaks.
    components: [samsung_ac]

# Configuration of AC component
samsung_ac:
  # Capabilities configure the features that all devices of your AC system have (all parts of this section are optional). 
  # All capabilities are off by default, you need to enable only those your devices have.
  # You can override or configure them also on a per-device basis (look below for that).
  capabilities: 
    vertical_swing: true
    horizontal_swing: true
    # Presets define special AC modes like Windfree, Eco, and so on. 
    # The following modes are available: sleep, quiet, fast, longreach, windfree, eco.
    presets: 
      # Short version - a quick and simple way to enable presets.
      quiet: true
      windfree: true
      sleep: true
      fast: true
      # Long version - allows customization, including localized names and control over enabling the presets.
      #fast:
      #  name: "Fast cooling"
      #  enabled: true

  devices:
    # Skip everything below on the first run! Wait a minute, watch your ESPHome logs until you see the "Discovered devices:" section and you see some addresses:
    # For NASA devices it looks like this (with 1 outdoor device and 4 indoor devices): 
       Outdoor: 10.00.00
       Indoor:  20.00.00, 20.00.01
      # Repeat everything below for each indoor device address you see in your logs
    - address: 20.00.00 # Indoor device address 
      capabilities:
        horizontal_swing: true
        vertical_swing: true 

      # Creates climate control in Home Assistant. A climate control combines multiple of the controls below (like temperature, mode etc.)
      climate:
        name: "AC menjador"

      # The controls directly below are all included in the climate control. Its adviced to only add the climate control and skip the extra controls.
      room_temperature:
        name: "Temperatura Menjador"
      target_temperature:
        name: "Temperatura desitjada Menjador"
      power:
        name: "Consum AC menjador"
      mode:
        name: "Mode"

      #Add automatic_cleaning mode for Samsung AC NASA
            #- Added the "automatic_cleaning" feature to the Samsung AC integration.
            #- This mode ensures hygienic drying of all moisture in the indoor unit after the cooling process is completed.
      automatic_cleaning:
        name: "AC Menjador automatic clean"

      # If your AC sits near or inside the ceiling, the reported room temperature is often a little bit heigher then whats 
      # measured below. This property can be used to correct that value.
      room_temperature_offset: -1.5

      # Only supported on NASA devices
      room_humidity:
        name: "Humitat AC Menjador"  
    - address: 10.00.00 # Outdoor device address as the following components are dependent on an outdoor unit.
      # This sensor captures and monitors specific error codes returned by the HVAC system.
      # When an error occurs, the sensor detects the error code and updates its value accordingly.
      # Additionally, by using the blueprint available at https://github.com/omerfaruk-aran/esphome_samsung_ac_blueprint,
      # you can automatically send detailed error messages to your mobile devices based on the captured error codes.
      error_code:
        name: error_code
        
      # This sensor measures the instantaneous power consumption of the outdoor unit in Watts.
      # The captured value represents the current power draw of the outdoor HVAC components, helping track energy usage patterns.
      outdoor_instantaneous_power:
        name: "Consum AC unitat exterior"

      # This sensor records the cumulative energy consumption of the outdoor unit in kWh.
      # It calculates the total energy consumed over time, allowing users to monitor and analyze energy efficiency.
      outdoor_cumulative_energy:
        name: "Acumulat consum AC unitat exterior"

      # This sensor measures the current drawn by the outdoor unit in Amperes.
      # Monitoring current values helps identify electrical irregularities and ensure safe power levels in the system.
      outdoor_current:
        name: "Corrent AC unitat exterior"

      # This sensor tracks the voltage supplied to the outdoor unit in Volts.
      # Consistent voltage readings indicate stable power delivery, while deviations can help detect electrical issues in the system.
      outdoor_voltage:
        name: "Voltatge AC unitat exterior"

      # Only supported on NASA based heatpumps
      #water_temperature:
       # name: "Warm water"
      #water_target_temperature:
       # name: "Hot Water Target Temperature"
      #water_heater_mode:
      #  name: "Hotwater Mode"
      #outdoor_temperature: # Should be used with outdoor device address
      #  name: "Outdoor temperature"
    -  address: 20.00.01 # Indoor device address 
      # Each property below is optional (climate, room_temperature etc.) - you can delete those which you dont need.
      # For the names we suggest to choose a combination of room name and the thing it controls. 

      # Configures/overrides the capabilites for this devices. 
      # Look above for all options.
      capabilities:
        horizontal_swing: true
        vertical_swing: true 

      # Creates climate control in Home Assistant. A climate control combines multiple of the controls below (like temperature, mode etc.)
      climate:
        name: "AC Dormitori"

      # The controls directly below are all included in the climate control. Its adviced to only add the climate control and skip the extra controls.
      room_temperature:
        name: "Temperatura Dormitori"
      target_temperature:
        name: "Temperatura desitjada Dormitori"
      power:
        name: "Consum AC dormitori"
      mode:
        name: "Mode"

      #Add automatic_cleaning mode for Samsung AC NASA
            #- Added the "automatic_cleaning" feature to the Samsung AC integration.
            #- This mode ensures hygienic drying of all moisture in the indoor unit after the cooling process is completed.
      automatic_cleaning:
        name: "AC Dormitori automatic clean"

      # If your AC sits near or inside the ceiling, the reported room temperature is often a little bit heigher then whats 
      # measured below. This property can be used to correct that value.
      room_temperature_offset: -1.5

      # Only supported on NASA devices
      room_humidity:
        name: "Humitat AC Dormitori"
```

### ESPHome Samsung AC Logs

<html>
<body>

23:13:23 | [D] | [climate:396] | 'Kitchen climate' - Sending state:
23:13:23 | [D] | [climate:399] | Mode: OFF
23:13:23 | [D] | [climate:407] | Custom Fan Mode: Turbo
23:13:23 | [D] | [climate:419] | Current Temperature: 26.00°C
23:13:23 | [D] | [climate:425] | Target Temperature: 24.00°C
23:13:25 | [D] | [sensor:094] | 'error_code': Sending state 0.00000  with 0 decimals of accuracy
23:13:25 | [D] | [sensor:094] | 'Outdoor temperature': Sending state 5.00000 °C with 1 decimals of accuracy
23:13:25 | [D] | [sensor:094] | 'Outdoor Current': Sending state 0.00000 A with 2 decimals of accuracy
23:13:28 | [D] | [sensor:094] | 'error_code': Sending state 0.00000  with 0 decimals of accuracy
23:13:31 | [D] | [sensor:094] | 'error_code': Sending state 0.00000  with 0 decimals of accuracy
23:13:33 | [D] | [sensor:094] | 'Kitchen temperature': Sending state 26.00000 °C with 1 decimals of accuracy
23:13:33 | [D] | [climate:396] | 'Kitchen climate' - Sending state:
23:13:33 | [D] | [climate:399] | Mode: OFF
23:13:33 | [D] | [climate:407] | Custom Fan Mode: Turbo
23:13:33 | [D] | [climate:419] | Current Temperature: 26.00°C
23:13:33 | [D] | [climate:425] | Target Temperature: 24.00°C
23:13:34 | [D] | [sensor:094] | 'error_code': Sending state 0.00000  with 0 decimals of accuracy
23:13:36 | [D] | [sensor:094] | 'Outdoor temperature': Sending state 5.00000 °C with 1 decimals of accuracy
23:13:36 | [D] | [sensor:094] | 'Outdoor Current': Sending state 0.00000 A with 2 decimals of accuracy
23:13:37 | [D] | [sensor:094] | 'error_code': Sending state 0.00000  with 0 decimals of accuracy
23:13:40 | [D] | [sensor:094] | 'error_code': Sending state 0.00000  with 0 decimals of accuracy
23:13:43 | [D] | [sensor:094] | 'error_code': Sending state 0.00000  with 0 decimals of accuracy
23:13:43 | [D] | [sensor:094] | 'Kitchen temperature': Sending state 26.00000 °C with 1 decimals of accuracy
23:13:43 | [D] | [climate:396] | 'Kitchen climate' - Sending state:
23:13:43 | [D] | [climate:399] | Mode: OFF
23:13:43 | [D] | [climate:407] | Custom Fan Mode: Turbo
23:13:43 | [D] | [climate:419] | Current Temperature: 26.00°C
23:13:43 | [D] | [climate:425] | Target Temperature: 24.00°C
23:13:46 | [D] | [sensor:094] | 'error_code': Sending state 0.00000  with 0 decimals of accuracy
23:13:47 | [D] | [sensor:094] | 'Outdoor temperature': Sending state 5.00000 °C with 1 decimals of accuracy
23:13:47 | [D] | [sensor:094] | 'Outdoor Current': Sending state 0.00000 A with 2 decimals of accuracy
23:13:49 | [D] | [sensor:094] | 'error_code': Sending state 0.00000  with 0 decimals of accuracy
23:13:50 | [D] | [device_state_tracker:046] | No change in value for device: 20.00.00
23:13:50 | [C] | [samsung_ac:053] | Configured devices: 10.00.00, 20.00.00
23:13:50 | [C] | [samsung_ac:065] | Discovered devices:
23:13:50 | [C] | [samsung_ac:066] | Outdoor: 10.00.00
23:13:50 | [C] | [samsung_ac:067] | Indoor:  20.00.00, 20.00.01
23:13:52 | [D] | [sensor:094] | 'error_code': Sending state 0.00000  with 0 decimals of accuracy
23:13:53 | [D] | [sensor:094] | 'Kitchen temperature': Sending state 26.00000 °C with 1 decimals of accuracy
23:13:53 | [D] | [climate:396] | 'Kitchen climate' - Sending state:
23:13:53 | [D] | [climate:399] | Mode: OFF
23:13:53 | [D] | [climate:407] | Custom Fan Mode: Turbo
23:13:53 | [D] | [climate:419] | Current Temperature: 26.00°C
23:13:53 | [D] | [climate:425] | Target Temperature: 24.00°C
23:13:55 | [D] | [sensor:094] | 'error_code': Sending state 0.00000  with 0 decimals of accuracy
23:13:58 | [D] | [sensor:094] |  

<br class="Apple-interchange-newline">
</body>
</html>
