### DISCUSSION TITLE
Calculating COP

### DISCUSSION THREAD

**Discussion by richjgould** [omerfaruk-aran/esphome_samsung_hvac_bus#253] [General]
Thanks all for this wonderful repo.

I have a Samsung Gen 7 Mono ASHP installed this week and making great progress with the M5STACK RS485 base.

I don't think that Coefficient of Performance exists as a register but can it be calculated on an ESPHome device on the fly?

In my yaml I have:

```

  devices:

    - address: "20.00.00"
  .......
      custom_sensor:
        - name: Total Produced Energy
          id: total_produced_energy
          message: 0x4427
          device_class: energy
          state_class: total_increasing
          unit_of_measurement: kWh

        - name: Current Produced Energy
          message: 0x4426
          id: instant_power_out
          device_class: energy
          state_class: measurement
          unit_of_measurement: W
          accuracy_decimals: 1

......

    - address: "10.00.00" # external unit
    ..... 
      custom_sensor:
        - name: Total Consumed Energy
          id: total_consumed_energy
          message: 0x8414
          device_class: energy
          state_class: total_increasing
          unit_of_measurement: kWh
          accuracy_decimals: 1
          filters:
            - multiply: 0.001

        - name: Power consumption
          id: instant_power_in
          message: 0x8413
          device_class: power
          state_class: measurement
          unit_of_measurement: W

''
```

and later...

```
`'
sensor:
   - platform: template
     name: Total COP
     filters:
     - lambda: return (id(total_produced_energy).raw_state) / (id(total_consumed_energy).raw_state);
     update_interval: 60s
     accuracy_decimals: 2

   - platform: template
     name: Instant COP
     filters:
      - lambda: return (id(instant_power_out).raw_state) / (id(instant_power_in).raw_state);
     update_interval: 10s     
     accuracy_decimals: 2

`'
```

The registers give me sensible values within home assistant but the template sensors are just 'unknown'.

Any ideas?
