### DISCUSSION TITLE
EHS Mono AE160CXYDEK/EU heat pump water outlet temperature setting

### DISCUSSION THREAD

**Discussion by stresserini** [omerfaruk-aran/esphome_samsung_hvac_bus#254] [Questions] [answered]
I have a new 16Kw R290 heat pump from Samsung.
via ESP I can get all the data in HA, but I'm racking my brain because the heating temperature setting of the radiators stops at 55 degrees, while via the "SmartThings" app I can get to 75 degrees as the set temperature.

The set temperature of the Hot Water (ACS), however, can regularly reach 70 degrees.

I have tried through various attempts to create "custom" sensors using NASA code, but I can't manage to get the sensor with the setting above 55 degrees.
This "number" value is read on the data that the pump gives, but I don't understand why, if via the app I can go forward up to 75

I entered my sensor configuration file and the sensor that I can't get above 55 degrees is the "water_outlet_target" which equates to NASA code 0x4247 (or so I think).

Can anyone help me having found the same problem?

![image](https://github.com/user-attachments/assets/3104fba9-4462-445c-bc5c-ea7afa8ab418)

![image](https://github.com/user-attachments/assets/0bf3dca0-f46f-4870-b49f-3c2178892085)

![Immagine WhatsApp 2025-01-18 ore 16 24 34_d0bb4de2](https://github.com/user-attachments/assets/9da4b94b-f417-41db-96b5-2a887ef283ed)

Mark

### Pre-Submission Checklist

- [X] I have searched for a similar question in open/closed issues.
- [X] I have checked the project’s documentation for relevant information.
- [X] I have provided as much detail as possible to help answer my question.

### HVAC System Type

NASA (Bus Protocol)

### Samsung HVAC Device Model

AE160CXYDEK/EU

### YAML Configuration

```yaml
external_components:
  - source: github://omerfaruk-aran/esphome_samsung_hvac_bus@main # use @main if you want the latest development (possibly unstable?)
    components: [samsung_ac]

# Configuration of AC component
samsung_ac:
  non_nasa_keepalive: false
  devices:
    - address: "20.00.00"
      water_temperature:
        name: "Temp. Boiler"
      power:
        name: "Pompa Riscaldamento ON/OFF"  
      water_heater_power:
        name: "Acqua calda ON/OFF" 
      water_outlet_target:
        name: "Set Temp Termosifoni"
      water_target_temperature:
        name: "Set Temp. ACS"   
      indoor_eva_in_temperature:
        name: "Temp Indoor In Riscaldamento" 
      indoor_eva_out_temperature:
        name: "Temp Indoor Out Riscaldamento"      
      custom_sensor:   
        - name: Water Flow
          message: 0x42E9
          state_class: measurement
          accuracy_decimals: 1
        - name: Target Termosofoni
          message: 0x4247
          id: water_target_temperature
                                                          
    - address: "10.00.00"      
      outdoor_temperature:
        name: "Temp. EXT Pompa"
      outdoor_instantaneous_power:
        name: "Outdoor Instantaneous Power"
      outdoor_current:
        name: "Outdoor Current"
      outdoor_voltage:
        name: "Outdoor Voltage"                   
      custom_sensor:  
        - name: Compressor Frequency
          message: 0x8238
          device_class: frequency
          state_class: measurement
          unit_of_measurement: Hz
          accuracy_decimals: 1
        - name: Target Compressor Frequency
          message: 0x8237
          device_class: frequency
          state_class: measurement
          unit_of_measurement: Hz
          accuracy_decimals: 1
        - name: Fan Speed
          message: 0x823D
          state_class: measurement
          unit_of_measurement: RPM
          accuracy_decimals: 1
        - name: Temperatura Mandata 30
          message: 0x82E0 
          unit_of_measurement: '°C'
          device_class: temperature
          state_class: measurement
        - name: Main EEV1
          message: 0x8229
          state_class: measurement
          accuracy_decimals: 1 
        - name: Water In TW1
          message: 0x82DF
          unit_of_measurement: '°C'
          device_class: temperature
          accuracy_decimals: 1 
        - name: Operation Mode
          message: 0x8001  
climate:        
    - platform: thermostat
      name: "Heating"
      id: climate_heating
      sensor: water_target_temperature
      min_heating_off_time: 300s
      min_heating_run_time: 300s    
      min_idle_time: 30s    
      heat_action: {}
      idle_action: {}
      visual:
        min_temperature: 30
        max_temperature: 75
        temperature_step:
          target_temperature: 1
          current_temperature: 0.1
```
