### DISCUSSION TITLE
Additional controls for FanSpeed and sleep- Non-NASA

### DISCUSSION THREAD

**Discussion by cjbrack** [omerfaruk-aran/esphome_samsung_hvac_bus#258] [Questions]
### Your Question

what is the correct yaml configuration to control the additional parameters?

### Additional Context

I want to enable fanspeed control as currently it defults to "auto" and doesn't allow further options to be selected, although it will report the current fanspeed of the airconditioner correctly in the logs, even if updated on the wall controller. The current configuration also doesn't show an option to enable the "sleep" and "quiet" modes. Note: I had to swap F1/F2 for my configuration to recognise the indoor unit correctly.
My attempts to try the names in the documentation get highlighted by the build checker as errors in the file and prevent building the device with them 'enabled'

### Pre-Submission Checklist

- [X] I have searched for a similar question in open/closed issues.
- [X] I have checked the project’s documentation for relevant information.
- [X] I have provided as much detail as possible to help answer my question.

### HVAC System Type

Non-NASA (Bus Protocol)

### ESP Device Model

M5STACK ATOM Lite + RS 485

### Connection Pins

F2/F1

### YAML Configuration

```yaml
# Specify pins used by the board to comunicate with RS485 board - in this case M5STACK
uart:
  tx_pin: GPIO19   # Use GPIO26 for ATOM Tail485 
  rx_pin: GPIO22   # Use GPIO32 for ATOM Tail485
  # For older devices it could also be 2400. But you should start with 9600.
  baud_rate: 9600
  parity: EVEN

## SAMSUNG AC CONFIGURATION

# Import custom component from GitHub
external_components:
  - source: github://omerfaruk-aran/esphome_samsung_hvac_bus@main # Use @stable if you want a more stable experience, but note a lot of this example code breaks.
    components: [samsung_ac]

# Configuration of AC component
samsung_ac:

  # For NonNASA devices the following option can be enabled to prevent the device from sleeping when idle. This allows
  # values like internal and external temperature to continue to be tracked when the device isn't in use.
  non_nasa_keepalive: true
  
  # When enabled (set to true), this option will log the messages associated with undefined codes on the device. This is useful for debugging and identifying any unexpected or unknown codes that the device may receive during operation.
  debug_log_undefined_messages: false
  
  # When enabled (set to true), this option logs messages associated with defined codes on the device. This helps in monitoring the behavior of the device by recording the activity related to known, expected codes.
  debug_log_messages: false

  # Capabilities configure the features that all devices of your AC system have (all parts of this section are optional). 
  # All capabilities are off by default, you need to enable only those your devices have.
  # You can override or configure them also on a per-device basis (look below for that).
  capabilities: 
    vertical_swing: false
    horizontal_swing: false
    # Presets define special AC modes like Windfree, Eco, and so on. 
    # The following modes are available: sleep, quiet, fast, longreach, windfree, eco.
    presets: 
      # Short version - a quick and simple way to enable presets.
      quiet: true
      sleep: true
      # Long version - allows customization, including localized names and control over enabling the presets.
      fast:
        name: "Fast cooling"
        enabled: true

  devices:
    # Repeat everything below for each indoor device address you see in your logs
    - address: "00" # Indoor device address 
      # Each property below is optional (climate, room_temperature etc.) - you can delete those which you dont need.
      # For the names we suggest to choose a combination of room name and the thing it controls. 

      # Configures/overrides the capabilites for this devices. 
      # Look above for all options.
      capabilities:
        horizontal_swing: false # This device have no h swing. 

      # Creates climate control in Home Assistant. A climate control combines multiple of the controls below (like temperature, mode etc.)
      climate:
        name: "Home climate"

      # The controls directly below are all included in the climate control. Its adviced to only add the climate control and skip the extra controls.
      room_temperature:
        name: "Home temperature"
      target_temperature:
        name: "Home target temperature"
      power:
        name: "Home power"
      mode:
        name: "Home mode"

      # If your AC sits near or inside the ceiling, the reported room temperature is often a little bit heigher then whats 
      # measured below. This property can be used to correct that value.
      room_temperature_offset: 0
      
    - address: "c8" # Outdoor device address as the following components are dependent on an outdoor unit.
      # This sensor captures and monitors specific error codes returned by the HVAC system.
      # When an error occurs, the sensor detects the error code and updates its value accordingly.
      # Additionally, by using the blueprint available at https://github.com/omerfaruk-aran/esphome_samsung_ac_blueprint,
      # you can automatically send detailed error messages to your mobile devices based on the captured error codes.
      error_code:
        name: error_code
```

### ESPHome Samsung AC Logs

10:55:03 | [D] | [climate:425] | Target Temperature: 22.00°C
10:55:03 | [D] | [climate:404] | Fan Mode: AUTO
10:55:03 | [D] | [climate:419] | Current Temperature: 22.00°C
10:55:03 | [D] | [climate:425] | Target Temperature: 22.00°C
10:55:03 | [D] | [select:015] | 'Home mode': Sending state Cool (index 1)
10:55:03 | [D] | [climate:396] | 'Home climate' - Sending state:
10:55:03 | [D] | [climate:399] | Mode: COOL
10:55:03 | [D] | [climate:404] | Fan Mode: AUTO
