### DISCUSSION TITLE
Using additional/external temp sensor

### DISCUSSION THREAD

**Discussion by Anat0m** [omerfaruk-aran/esphome_samsung_hvac_bus#272] [Questions] [answered]
### Your Question

How to add additional/external temp sensor?

### Additional Context

Hi, I’m currently managing two AC units whose controls work well, but I’m noticing that the temperature readings seem off. I have a Zigbee temperature sensor installed in the same room, but it is positioned a bit farther from the AC unit - I consider it the _correct_ temperature value. My main goal is to achieve more accurate temperature reporting.

Specifically, I’m exploring two potential solutions:
	1.	Creating a custom climate card (**or modifying the default one**) that uses the temperature reading from the external Zigbee sensor instead of the built-in sensor value, or
	2.	Implementing a dynamic adjustment to the room_temperature_offset that effectively compensates for the sensor placement difference.

Alternatively, I’m curious if it’s feasible to combine data from both sensors—the one integrated in the AC unit and the external Zigbee sensor—to enhance overall accuracy.

Any guidance on how to implement these approaches or suggestions for alternative solutions would be appreciated.

### Pre-Submission Checklist

- [X] I have searched for a similar question in open/closed issues.
- [X] I have checked the project’s documentation for relevant information.
- [X] I have provided as much detail as possible to help answer my question.

### HVAC System Type

NASA (Bus Protocol)

### Samsung HVAC Device Model

AJ052TXJ3KG/EU + AR09TXFCAWKNEU + AR12TXFCAWKNEU

### ESP Device Model

M5STACK ATOM Lite + M5STACK RS-458

### Connection Pins

F1/F2

### YAML Configuration

```yaml
esphome:
  name: esp-home-ac-manager
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: m5stack-atom

# Enable logging
logger:
  logs:
    component: ERROR # Remove the "Your component takes to long to respond warning"

# Enable Home Assistant API
api:
  encryption:
    key: "HIDDEN"

# Allow Over-The-Air updates
ota:
  platform: esphome
  password: "HIDDEN"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  power_save_mode: none
  
  manual_ip:
    static_ip: 192.168.3.112
    gateway: 192.168.3.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-AC-Manager"
    password: "HIDDEN"

# Specify pins used by the board to comunicate with RS485 board - in this case M5STACK
uart:
  tx_pin: GPIO19   # Use GPIO26 for ATOM Tail485 
  rx_pin: GPIO22   # Use GPIO32 for ATOM Tail485
  # For older devices it could also be 2400. But you should start with 9600.
  baud_rate: 9600
  parity: EVEN

# Import custom component from GitHub
external_components:
  - source: github://omerfaruk-aran/esphome_samsung_hvac_bus@main # Use @stable if you want a more stable experience, but note a lot of this example code breaks.
    components: [samsung_ac]

# Configuration of AC component
samsung_ac:

  # For NonNASA devices the following option can be enabled to prevent the device from sleeping when idle. This allows
  # values like internal and external temperature to continue to be tracked when the device isn't in use.
  non_nasa_keepalive: true
  
  # When enabled (set to true), this option will log the messages associated with undefined codes on the device. This is useful for debugging and identifying any unexpected or unknown codes that the device may receive during operation.
  debug_log_undefined_messages: false
  
  # When enabled (set to true), this option logs messages associated with defined codes on the device. This helps in monitoring the behavior of the device by recording the activity related to known, expected codes.
  debug_log_messages: false

  # Capabilities configure the features that all devices of your AC system have (all parts of this section are optional). 
  # All capabilities are off by default, you need to enable only those your devices have.
  # You can override or configure them also on a per-device basis (look below for that).
  capabilities: 
    vertical_swing: true
    horizontal_swing: true
    presets: 
      quiet: true
      windfree: true
      fast: true

    # Skip everything below on the first run! Wait a minute, watch your ESPHome logs until you see the "Discovered devices:" section and you see some addresses:
    # For NASA devices it looks like this (with 1 outdoor device and 4 indoor devices): 
    #   Outdoor: 10.00.00
    #   Indoor:  20.00.00, 20.00.01, 20.00.02, 20.00.03
    # For NonNASA devices it looks like this (with 2 indoor devices): 
    #   Indoor:  00, 01
    # You need these addresses for the the sections below. If you see only a "-" then you should visit the troubleshooting section in the readme. 
  devices:
    # Repeat everything below for each indoor device address you see in your logs
    - address: "20.00.00" # Indoor device address 
      # Each property below is optional (climate, room_temperature etc.) - you can delete those which you dont need.
      # For the names we suggest to choose a combination of room name and the thing it controls. 

      # Configures/overrides the capabilites for this devices. 
      # Look above for all options.
      capabilities:
        horizontal_swing: true # This device have no h swing. 
        vertical_swing: true
        presets: 
          quiet: true
          windfree: true
          fast: true
      # Creates climate control in Home Assistant. A climate control combines multiple of the controls below (like temperature, mode etc.)
      climate:
        name: "Living room climate"

      # The controls directly below are all included in the climate control. Its adviced to only add the climate control and skip the extra controls.
      room_temperature:
        name: "Living room temperature"
      target_temperature:
        name: "Living room target temperature"
      power:
        name: "Living room power"
      mode:
        name: "Living room mode"

      #Add automatic_cleaning mode for Samsung AC NASA
            #- Added the "automatic_cleaning" feature to the Samsung AC integration.
            #- This mode ensures hygienic drying of all moisture in the indoor unit after the cooling process is completed.
      automatic_cleaning:
        name: "Living room automatic clean"

      # If your AC sits near or inside the ceiling, the reported room temperature is often a little bit heigher then whats 
      # measured below. This property can be used to correct that value.
      room_temperature_offset: -1.4

      # Only supported on NASA devices
      room_humidity:
        name: "Living room humidity"

    - address: "20.00.01" # Indoor device address 
      # Each property below is optional (climate, room_temperature etc.) - you can delete those which you dont need.
      # For the names we suggest to choose a combination of room name and the thing it controls. 

      # Configures/overrides the capabilites for this devices. 
      # Look above for all options.
      capabilities:
        horizontal_swing: true # This device have no h swing. 
        vertical_swing: true
        presets: 
          quiet: true
          windfree: true
          fast: true
      # Creates climate control in Home Assistant. A climate control combines multiple of the controls below (like temperature, mode etc.)
      climate:
        name: "Bedroom climate"

      # The controls directly below are all included in the climate control. Its adviced to only add the climate control and skip the extra controls.
      room_temperature:
        name: "Bedroom temperature"
      target_temperature:
        name: "Bedroom target temperature"
      power:
        name: "Bedroom power"
      mode:
        name: "Bedroom mode"

      #Add automatic_cleaning mode for Samsung AC NASA
            #- Added the "automatic_cleaning" feature to the Samsung AC integration.
            #- This mode ensures hygienic drying of all moisture in the indoor unit after the cooling process is completed.
      automatic_cleaning:
        name: "Bedroom automatic clean"

      # If your AC sits near or inside the ceiling, the reported room temperature is often a little bit heigher then whats 
      # measured below. This property can be used to correct that value.
      room_temperature_offset: -1.4

      # Only supported on NASA devices
      room_humidity:
        name: "Bedroom humidity"      

    - address: "10.00.00" # Outdoor device address as the following components are dependent on an outdoor unit.
      # This sensor captures and monitors specific error codes returned by the HVAC system.
      # When an error occurs, the sensor detects the error code and updates its value accordingly.
      # Additionally, by using the blueprint available at https://github.com/omerfaruk-aran/esphome_samsung_ac_blueprint,
      # you can automatically send detailed error messages to your mobile devices based on the captured error codes.
      error_code:
        name: error_code
        
      # This sensor measures the instantaneous power consumption of the outdoor unit in Watts.
      # The captured value represents the current power draw of the outdoor HVAC components, helping track energy usage patterns.
      outdoor_instantaneous_power:
        name: "Outdoor Instantaneous Power"

      # This sensor records the cumulative energy consumption of the outdoor unit in kWh.
      # It calculates the total energy consumed over time, allowing users to monitor and analyze energy efficiency.
      outdoor_cumulative_energy:
        name: "Outdoor Cumulative Energy"

      # This sensor measures the current drawn by the outdoor unit in Amperes.
      # Monitoring current values helps identify electrical irregularities and ensure safe power levels in the system.
      outdoor_current:
        name: "Outdoor Current"

      # This sensor tracks the voltage supplied to the outdoor unit in Volts.
      # Consistent voltage readings indicate stable power delivery, while deviations can help detect electrical issues in the system.
      outdoor_voltage:
        name: "Outdoor Voltage"
```
