### ISSUE TITLE
`Bug` [Samsung_HVAC]: HVAC does not start until the second try

### ISSUE THREAD

**Issue by mbo18** [omerfaruk-aran/esphome_samsung_hvac_bus#221]
### The problem

I have this issue on all my units: when it has been off for several hours, when I set the HVAC from off to heat or cold, the unit does not go on. It stay off and I need to do it a second time.

Note that since the latest update to the code, this issue is only when I need to start the unit. When on, all commands are correctly executed on the first try (thank you for this!)

I will try to get logs and will update this issue

### ESPHome Version

2024.10.2

### Samsung HVAC Component Version

Latest from main

### Home Assistant Version

2024.10.4

### AC Type

NASA

### Indoor AC Unit Model

AR09TXCAAWKN

### Outdoor AC Unit Model

AR09TXCAAWKX

### ESP Device Model

M5stack atom lite + m5stack rs485

### Connection Points

F1/F2

### YAML Configuration

```yaml
esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

uart:
  tx_pin: GPIO19
  rx_pin: GPIO22
  baud_rate: 9600
  parity: EVEN

external_components:
  - source: github://omerfaruk-aran/esphome_samsung_hvac_bus@main
    components: [samsung_ac]

samsung_ac:
  debug_log_messages_raw: false
  debug_log_messages: false
  capabilities:
    vertical_swing: true
    horizontal_swing: true
    presets: 
      quiet: true
      windfree: true
      fast: true
  devices:
    - address: "20.00.00"
      climate:
        name: None
      room_temperature_offset: -2.0
      automatic_cleaning:
        name: "Automatic cleaning"
    - address: "10.00.00"
      outdoor_temperature:
        name: "Outdoor temperature"
      outdoor_instantaneous_power:
        name: "Power"
        accuracy_decimals: 0
      outdoor_cumulative_energy:
        name: "Energy"
        accuracy_decimals: 2
```
