### ISSUE TITLE
`Bug` [Samsung_HVAC]: Project reporting higher indoor temp than SmartThings or AC itself

### ISSUE THREAD

**Issue by techyporcupine** [omerfaruk-aran/esphome_samsung_hvac_bus#225]
### The problem

Hello! I noticed recently that the Samsung HVAC component seems to report noticeably higher indoor temperatures than what the AC has on its display or in SmartThings. For instance, my AC is set to 62, says 64, but in Home Assistant it is displayed as 68. 

I thought about changing `room_temperature_offset` but if the AC is reporting the correct temp that shouldn't be needed?

### ESPHome Version

2024.10.2

### Samsung HVAC Component Version

latest

### Home Assistant Version

2024.11.2

### AC Type

NASA

### Indoor AC Unit Model

AR12TSFABWKNCV

### Outdoor AC Unit Model

AR12TSFACWKX

### ESP Device Model

M5STAMP Pico

### Connection Points

F1/F2

### YAML Configuration

```yaml
devices:
    # Skip everything below on the first run! Wait a minute, watch your ESPHome logs until you see the "Discovered devices:" section and you see some addresses:
    # For NASA devices it looks like this (with 4 indoor devices): 
    #   Indoor:  20.00.00, 20.00.01, 20.00.02, 20.00.03
    # For NonNASA devices it looks like this (with 2 indoor devices): 
    #   Indoor:  00, 01
    # You need this addresses for the the sections below. If you see only a "-" then you should visit the troubleshooting section in the readme. 

    # Repeat everything below for each indoor device address you see in your logs
    - address: "20.00.00" # Indoor device address 
      # Each property below is optional (climate, room_temperature etc.) - you can delete those which you dont need.
      # For the names we suggest to choose a combination of room name and the thing it controls. 

      # Creates climate control in Home Assistant. A climate control combines multiple of the controls below (like temperature, mode etc.)
      climate:
        name: "SunroomAC"

      # The controls directly below are all included in the climate control. Its adviced to only add the climate control and skip the extra controls.
      room_temperature:
        name: "Indoor Temperature"
        id: sunroomac_temp

      # If your AC sits near or inside the ceiling, the reported room temperature is often a little bit heigher then whats 
      # measured below. This property can be used to correct that value.
      # room_temperature_offset: -1.4

      # Only supported on NASA devices
      room_humidity:
        name: "Indoor Humidity"
      

    - address: "10.00.00"
      # This sensor captures and monitors specific error codes returned by the HVAC system.
      # When an error occurs, the sensor detects the error code and updates its value accordingly.
      # Additionally, by using the blueprint available at https://github.com/omerfaruk-aran/esphome_samsung_ac_blueprint,
      # you can automatically send detailed error messages to your mobile devices based on the captured error codes.
      error_code:
        name: "Error Code"

      # Only supported on NASA based heatpumps
      outdoor_temperature: # Should be used with outdoor device address
        name: "Outdoor Temperature"
        
      # This sensor measures the instantaneous power consumption of the outdoor unit in Watts.
      # The captured value represents the current power draw of the outdoor HVAC components, helping track energy usage patterns.
      outdoor_instantaneous_power:
        name: "Outdoor Power"

      # This sensor records the cumulative energy consumption of the outdoor unit in kWh.
      # It calculates the total energy consumed over time, allowing users to monitor and analyze energy efficiency.
      outdoor_cumulative_energy:
        name: "Outdoor Cumulative Energy"
```

**Comment by dierkgrossfeld** [comment]
Maybe I can help out here.
There is according to the documentation of nasa a modified temperature under Address:
0x4204
for each indoor device.
I am monitoring this one since yesterday and it seems to be pretty accurately the temperature that is also shown on the indoor devices.

Maybe it could be exchanged to this on on the climate controls.....

**Comment by techyporcupine** [comment]
What config did you use? I tried mine like this and it's reporting 412 degrees Fahrenheit
```
      custom_sensor:
      - name: "Indoor Temperature Fixed"
        id: sunroomac_temp_fix
        message: 0x4204
        device_class: temperature
        state_class: measurement
        unit_of_measurement: "°C"
```

**Comment by Jkirjo** [comment]
> What config did you use? I tried mine like this and it's reporting 412 degrees Fahrenheit
> 
> ```
>       custom_sensor:
>       - name: "Indoor Temperature Fixed"
>         id: sunroomac_temp_fix
>         message: 0x4204
>         device_class: temperature
>         state_class: measurement
>         unit_of_measurement: "°C"
> ```

Tested also this. I got 200C when indoor unit shows 20C, and the real measured temp is 21C.
Mine:
```
custom_sensor:
        - name: Korjattu lämpö
          message: 0x4204
          device_class: temperature
          state_class: measurement
          unit_of_measurement: "°C"
```

**Comment by techyporcupine** [comment]
Doing this seems to work perfectly for me.
```yaml
      custom_sensor:
      - name: "Indoor Temperature Fixed"
        id: sunroomac_temp_fix
        message: 0x4204
        device_class: temperature
        state_class: measurement
        unit_of_measurement: "°C"
        accuracy_decimals: 2
        #Add filter as it reports with an extra zero
        filters:
        - multiply: 0.1
```
 @dierkgrossfeld Does yours also report with the decimal in the wrong location?

I'm going to figure out how to override what is set for the climate entity.
