### ISSUE TITLE
`Bug` [Samsung_HVAC]: commands are not executed

### ISSUE THREAD

**Issue by Code394** [omerfaruk-aran/esphome_samsung_hvac_bus#229]
### The problem

that I give orders to several air conditioners at the same time
every time Some air conditioners do not accept the command
(different air conditioners each time)
When a command fails, it creates endless messages of
[21:32:01][W][samsung_ac:902]: Packet 54 failed after 3 attempts.
[21:32:01][W][samsung_ac:902]: Packet 55 failed after 3 attempts.
[21:32:01][W][samsung_ac:902]: Packet 6 failed after 3 attempts.
[21:32:01][W][samsung_ac:902]: Packet 26 failed after 3 attempts.
[21:32:01][W][samsung_ac:902]: Packet 28 failed after 3 attempts.
But apparently he doesn't really send a command again
Because if I give them command separately, The air conditioners do carry out the orders

The situation has significantly improved since the merge of Pull Request #206 
Only further improvement to the mechanism is required

It should be noted that when using the fork of [atanasenko](https://github.com/atanasenko/esphome_samsung_ac/tree/transport), The commands work fine
If you need further tests I am so for you

Thank you for your work for the project

### ESPHome Version

2024.11.2

### Samsung HVAC Component Version

30/11/2024

### Home Assistant Version

2024.11.3

### AC Type

NASA

### Indoor AC Unit Model

Global Mini4Way, 360CST, Fresh Ouct

### Outdoor AC Unit Model

unknown

### ESP Device Model

WT32-ETH01 + Grove-RS485

### Connection Points

F1/F2

### ESPHome Logs

[logs_1_logs.txt](https://github.com/user-attachments/files/17966601/logs_1_logs.txt)
[logs_1_logs (1).txt](https://github.com/user-attachments/files/17966602/logs_1_logs.1.txt)

### YAML Configuration

```yaml
## BASIC CONFIGURATION
esphome:
  name: samsung_ac
  friendly_name: Climate

esp32:
  board: 'wt32-eth01'
  framework:
    type: arduino
  
ethernet:
  type: 'LAN8720'
  mdc_pin: 'GPIO23'
  mdio_pin: 'GPIO18'
  clk_mode: 'GPIO0_IN'
  phy_addr: 1
  power_pin: 'GPIO16'
  
web_server:
  port: 80

# Enable logging
logger:
  #level: INFO #DEBUG
  logs:
    component: ERROR # Remove the "Your component takes to long to respond warning"

# Enable Home Assistant API
api:
  encryption:
    key: "####"

ota:
  - platform: esphome

# Specify pins used by the board to comunicate with RS485 board - in this case M5STACK
uart:
  id: uart_bus
  tx_pin: GPIO17   # Use GPIO26 for ATOM Tail485 
  rx_pin: GPIO5   # Use GPIO32 for ATOM Tail485
  # For older devices it could also be 2400. But you should start with 9600.
  baud_rate: 9600
  parity: EVEN

# Example configuration entry
button:
  - platform: factory_reset
    name: Restart with Factory Default Settings

## SAMSUNG AC CONFIGURATION

# Import custom component from GitHub
external_components:
  - source: github://omerfaruk-aran/esphome_samsung_hvac_bus@main # use @main if you want the latest development (possibly unstable?)
    components: [samsung_ac]

# Configuration of AC component
samsung_ac:

  # For NonNASA devices the following option can be enabled to prevent the device from sleeping when idle. This allows
  # values like internal and external temperature to continue to be tracked when the device isn't in use.
  non_nasa_keepalive: true
  
  # When enabled (set to true), this option will log the messages associated with undefined codes on the device. This is useful for debugging and identifying any unexpected or unknown codes that the device may receive during operation.
  debug_log_undefined_messages: false
  
  # When enabled (set to true), this option logs messages associated with defined codes on the device. This helps in monitoring the behavior of the device by recording the activity related to known, expected codes.
  debug_log_messages: false

  # Capabilities configure the features that all devices of your AC system have (all parts of this section are optional). 
  # All capabilities are off by default, you need to enable only those your devices have.
  # You can override or configure them also on a per-device basis (look below for that).
  capabilities: 
    vertical_swing: true
    horizontal_swing: true
    # Presets define special AC modes like Windfree, Eco, and so on. 
    # The following modes are available: sleep, quiet, fast, longreach, windfree, eco.
    presets: 
      # Short version - a quick and simple way to enable presets.
      quiet: true
      # Long version - allows customization, including localized names and control over enabling the presets.
      fast:
        name: "Fast cooling"
        enabled: true

  devices:

  - address: "20.01.00" # Indoor device address 
    capabilities:
      horizontal_swing: true
    climate:
      name: "L3"
      visual:
       min_temperature: 18
       temperature_step: 0.5
    error_code:
      name: "L3 Error Code"

  - address: "20.01.01" # Indoor device address 
    capabilities:
      horizontal_swing: true
    climate:
      name: "R4"
      visual:
       min_temperature: 18
       temperature_step: 0.5
    error_code:
      name: "R4 Error Code"

  - address: "20.01.02" # Indoor device address 
    capabilities:
      horizontal_swing: true
    climate:
      name: "L4"
      visual:
       min_temperature: 18
       temperature_step: 0.5
    error_code:
      name: "L4 Error Code"

  - address: "20.01.03" # Indoor device address 
    climate:
      name: "mid 3"
      visual:
       min_temperature: 18
       temperature_step: 0.5
    error_code:
      name: "mid 3 Error Code"

  - address: "20.01.04" # Indoor device address 
    capabilities:
      horizontal_swing: true
    climate:
      name: "R1"
      visual:
       min_temperature: 18
       temperature_step: 0.5
    error_code:
      name: "R1 Error Code"

  - address: "20.01.05" # Indoor device address 
    climate:
      name: "mid 4"
      visual:
       min_temperature: 18
       temperature_step: 0.5
    error_code:
      name: "mid 4 Error Code"

  - address: "20.01.06" # Indoor device address 
    capabilities:
      horizontal_swing: true
    climate:
      name: "L1"
      visual:
       min_temperature: 18
       temperature_step: 0.5
    error_code:
      name: "L1 Error Code"

  - address: "20.01.07" # Indoor device address 
    capabilities:
      horizontal_swing: true
    climate:
      name: "R3"
      visual:
       min_temperature: 18
       temperature_step: 0.5
    error_code:
      name: "R3 Error Code"

  - address: "20.01.08" # Indoor device address 
    capabilities:
      horizontal_swing: true
    climate:
      name: "R2"
      visual:
       min_temperature: 18
       temperature_step: 0.5
    error_code:
      name: "R2 Error Code"

  - address: "20.01.09" # Indoor device address 
    capabilities:
      horizontal_swing: true
    climate:
      name: "L2"
      visual:
       min_temperature: 18
       temperature_step: 0.5
    error_code:
      name: "L2 Error Code"

  - address: "20.01.0a" # Indoor device address 
    climate:
      name: "mid 2"
      visual:
       min_temperature: 18
       temperature_step: 0.5
    error_code:
      name: "mid 2 Error Code"

  - address: "20.01.0b" # Indoor device address 
    climate:
      name: "mid 1"
      visual:
       min_temperature: 18
       temperature_step: 0.5
    error_code:
      name: "mid 1 Error Code"

  - address: "20.01.0c" # Indoor device address 
    capabilities:
      horizontal_swing: false
      vertical_swing: false
    climate:
      name: "avir"
      visual:
       min_temperature: 18
       temperature_step: 0.5
    error_code:
      name: "avir Error Code"

  - address: "20.01.0d" # Indoor device address 
    climate:
      name: "1"
      visual:
       min_temperature: 18
       temperature_step: 0.5
    error_code:
      name: "1 Error Code"

  - address: "20.01.0e" # Indoor device address 
    climate:
      name: "bl"
      visual:
       min_temperature: 18
       temperature_step: 0.5
    error_code:
      name: "7bl Error Code"

  - address: "20.01.0f" # Indoor device address 
    climate:
      name: "fl"
      visual:
       min_temperature: 18
       temperature_step: 0.5
    error_code:
      name: "fl Error Code"

  - address: "20.01.10" # Indoor device address 
    climate:
      name: "br"
      visual:
       min_temperature: 18
       temperature_step: 0.5
    error_code:
      name: "8br Error Code"

  - address: "20.01.11" # Indoor device address 
    climate:
      name: "fr"
      visual:
       min_temperature: 18
       temperature_step: 0.5
    error_code:
      name: "16fr Error Code"

  - address: "20.01.12" # Indoor device address 
    climate:
      name: "3"
      visual:
       min_temperature: 18
       temperature_step: 0.5
    error_code:
      name: "3 Error Code"

  - address: "20.01.13" # Indoor device address 
    climate:
      name: "2"
      visual:
       min_temperature: 18
       temperature_step: 0.5
    error_code:
      name: "2 Error Code"

  - address: "20.01.14" # Indoor device address 
    climate:
      name: "4"
      visual:
       min_temperature: 18
       temperature_step: 0.5
    error_code:
      name: "4 Error Code"

  - address: "10.01.00" # Outdoor device address as the following components are dependent on an outdoor unit.
    error_code:
      name: error_code_00

    outdoor_instantaneous_power:
      name: "Outdoor Instantaneous Power 00"

    outdoor_cumulative_energy:
      name: "Outdoor Cumulative Energy 00"

    outdoor_current:
      name: "Outdoor Current 00"

    outdoor_voltage:
      name: "Outdoor Voltage 00"

  - address: "10.01.01" # Outdoor device address as the following components are dependent on an outdoor unit.
    error_code:
      name: error_code_01

    outdoor_instantaneous_power:
      name: "Outdoor Instantaneous Power 01"

    outdoor_cumulative_energy:
      name: "Outdoor Cumulative Energy 01"

    outdoor_current:
      name: "Outdoor Current 01"

    outdoor_voltage:
      name: "Outdoor Voltage 01"
```
