### ISSUE TITLE
`Bug` [Samsung_HVAC]:  water_target_temperature on_value does not fire

### ISSUE THREAD

**Issue by Beormund** [omerfaruk-aran/esphome_samsung_hvac_bus#234]
### The problem

If water_target_temperature is updated via Home Assistant UI, ESPHome Web UI or via SmartThings on_value does not fire so the update cannot be passed on to a Thermostat Climate control. 

### ESPHome Version

2024.11.3

### Samsung HVAC Component Version

20240213.1

### Home Assistant Version

2024.12

### AC Type

NASA

### Indoor AC Unit Model

mim-e03cn

### Outdoor AC Unit Model

AE120RXYDEG/EU

### ESP Device Model

lilygo t rss3 esp32 s3

### Connection Points

F1/F2

### YAML Configuration

```yaml
water_target_temperature:
        name: "DHW Target Temperature"
        id: hot_water_target_temp
        on_value:
          then:
            - logger.log:
                level: INFO
                format: "x: %f; DHW Target Temp: %f"
                args: ['x', 'id(climate_hot_water).target_temperature']
            - if:
                condition:
                  lambda: "return x != id(climate_hot_water).target_temperature;"
                then:
                  - climate.control:
                      id: climate_hot_water
                      target_temperature: !lambda "return x;"
```
