### ISSUE TITLE
[COMMON] Set Correct Default Icon for Automatic Cleaning Mode

### ISSUE THREAD

**Issue by bzumik1** [omerfaruk-aran/esphome_samsung_hvac_bus#249]
### The problem

Hi, this is just minor think, but it would be nice if we could use `mdi:broom` icon for automatic cleaning mode. Currently I need to specify it manually like this.

```yaml
      automatic_cleaning:
        name: "ložnice automatické čištění"
        icon: mdi:broom
```

<img width="316" alt="image" src="https://github.com/user-attachments/assets/5e94dbdb-83eb-4c54-957a-f50fa7baf485" />

### ESPHome Version

Not Relevant

### Samsung HVAC Component Version

Not Relevant

### Home Assistant Version

Not Relevant

### AC Type

NASA

### Indoor AC Unit Model

Not Relevant

### Outdoor AC Unit Model

Not Relevant

### ESP Device Model

Not Relevant

### Connection Points

Not Relevant

### ESPHome Logs

Not Relevant

### Samsung AC Logs

Not Relevant

### YAML Configuration

```yaml
automatic_cleaning:
        name: "ložnice automatické čištění"
        icon: mdi:broom
```
