### ISSUE TITLE
problem only Tx

### ISSUE THREAD

**Issue by wifi75** [omerfaruk-aran/esphome_samsung_hvac_bus#270]
### The problem

hello I have an external unit and 2 internal ones, 

the problem is that I can view all the changes that occur via the remote control via HA, but if I try to turn on or off or change the temperature from HA, these do not work. it seems that the tx does not work.

I currently only have one external drive enabled.

What can I check?

### ESPHome Version

2025.3.3 

### Samsung HVAC Component Version

20240213.1

### Home Assistant Version

2025.4.0

### AC Type

NON NASA

### Indoor AC Unit Model

AR12HSSDBWKNEU

### Outdoor AC Unit Model

AJ040FCJ2EH

### ESP Device Model

M5STACK ATOM Lite + M5STACK ATOM RS-485 Base

### Connection Points

f1,f2

### ESPHome Logs

[logs_samsung_logs.txt](https://github.com/user-attachments/files/19601527/logs_samsung_logs.txt)

### YAML Configuration

```yaml
esphome:
  name: ac-rooms
  friendly_name: ac-rooms

esp32:
  board: m5stack-atom
  

web_server:
  port: 80

logger:
  level: INFO
  logs:
    component: ERROR # Remove the "Your component takes to long to respond warning"

api:


ota:
  - platform: esphome


# Setup your WiFi password
wifi:
  ssid: "WiFi" # !!!CHANGE ME!!!
  password: "12345678901234567890" # !!!CHANGE ME!!!
  manual_ip:
    static_ip: 192.168.1.168
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1

captive_portal:

#uart:
#  tx_pin: GPIO19 # Use GPIO26 for ATOM Tail485 
#  rx_pin: GPIO22  # Use GPIO32 for ATOM Tail485
#  baud_rate: 9600
#  parity: EVEN


#################################
#### UART SETUP/DECODE BYTES ####
#################################

uart:
  id: uart_bus
  tx_pin: 19
  rx_pin: 22
  baud_rate: 9600
  data_bits: 8
  stop_bits: 1
  parity: EVEN
  debug:
    direction: BOTH
    dummy_receiver: false
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_hex(direction, bytes, ' ');

external_components:
  - source: github://tristone-cz/esphome_samsung_hvac_bus@patch-slow-registration  
    components: [samsung_ac]
    refresh: 0s

# Configuration of AC component


samsung_ac:
  non_nasa_keepalive: false
  debug_log_undefined_messages: true
  debug_log_messages: true
  capabilities: 
    vertical_swing: true
    presets: 
      quiet: true
      fast: true
      windfree: true

  devices:
    - address: "c8" # Outdoor device address

    - address: "00" # Indoor device address 
      capabilities:
        horizontal_swing: true  
      climate:
        name: "Soggiorno AC"
      room_temperature:
        name: "Soggiorno AC temperature"
      target_temperature:
        name: "Soggiorno AC target"
      power:
        name: "Soggiorno AC power"
      mode:
        name: "Soggiorno AC mode"
      room_temperature_offset: 0
      error_code:
        name: "Error Code"
 #   - address: "01" # Indoor device address 
 #     capabilities:
 #       horizontal_swing: true  
 #     climate:
 #       name: "Matrimoniale AC"
 #     room_temperature:
 #       name: "Matrimoniale AC temperature"
 #     target_temperature:
 #       name: "Matrimoniale AC target"
 #     power:
 #       name: "Matrimoniale AC power"
 #     mode:
 #       name: "Matrimoniale AC mode"
 #     room_temperature_offset: 0
 #     error_code:
 #       name: "Error Code"
```
