### ISSUE TITLE
`Bug` [Samsung_HVAC]: Openhab via MQTT: preset-mode receives command (not string) 'none'.

### ISSUE THREAD

**Issue by karelvhouten** [omerfaruk-aran/esphome_samsung_hvac_bus#271]
### The problem

Samsung NASA device connected via ESPHome and MQTT to Openhab. When indoor unit is off, the <device>#preset-mode mqtt channel keeps receiving a 'none' value, which is not a valid type for a text string. As soon as the indoor unit is on, and a specific preset is selected, a string is send, for example "quiet". Then all is well. How can I translate the 'no preset selected' situation to the STRING "None" (not an empty value).

Openhab gives this warning message about every second:
`2025-04-09 16:22:50.687 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'none' from channel 'mqtt:homeassistant:mosquitto:samsung-ac:slaapkamer_ac#preset-mode' not supported by type 'TextValue': Value none not within range`

Thanks in advance!

### ESPHome Version

2025.2.2q

### Samsung HVAC Component Version

Current main

### Home Assistant Version

N.a. Openhab version

### AC Type

NASA

### Indoor AC Unit Model

AR09TXFCAWKN

### Outdoor AC Unit Model

AJ068TXJ3KG-EU

### ESP Device Model

M5STACK ATOM Lite + M5STACK RS485

### Connection Points

F1/F2 in outside unit

### Samsung AC Logs

[16:28:58][C][samsung_ac:053]: Configured devices: 10.00.00, 20.00.00, 20.00.01, 20.00.02
[16:28:58][C][samsung_ac:065]: Discovered devices:
[16:28:58][C][samsung_ac:066]:   Outdoor: 10.00.00
[16:28:58][C][samsung_ac:067]:   Indoor:  20.00.00, 20.00.01, 20.00.02
[16:28:59][W][samsung_ac:594]: s:20.00.00 d:b0.00.ff VAR_in_temp_room_f 18.8
[16:28:59][D][sensor:094]: 'Caroline AC temperature': Sending state 18.80000 °C with 1 decimals of accuracy
[16:28:59][D][climate:396]: 'Caroline AC' - Sending state:
[16:28:59][D][climate:399]:   Mode: OFF
[16:28:59][D][climate:404]:   Fan Mode: AUTO
[16:28:59][D][climate:410]:   Preset: NONE
[16:28:59][D][climate:416]:   Swing Mode: OFF
[16:28:59][D][climate:419]:   Current Temperature: 18.80°C
[16:28:59][D][climate:425]:   Target Temperature: 21.00°C
[16:28:59][W][samsung_ac:709]: s:20.00.00 d:b0.00.ff VAR_in_temp_eva_in_f 19.4
[16:28:59][W][samsung_ac:716]: s:20.00.00 d:b0.00.ff VAR_in_temp_eva_out_f 19.3
[16:28:59][W][samsung_ac:725]: s:10.00.00 d:b0.00.ff VAR_out_error_code 0
[16:28:59][D][sensor:094]: 'error_code': Sending state 0.00000  with 0 decimals of accuracy
[16:28:59][W][samsung_ac:594]: s:20.00.01 d:b0.00.ff VAR_in_temp_room_f 22.8
[16:28:59][D][sensor:094]: 'Logeerkamer AC temperature': Sending state 22.80000 °C with 1 decimals of accuracy
[16:28:59][D][climate:396]: 'Logeerkamer AC' - Sending state:
[16:28:59][D][climate:399]:   Mode: OFF
[16:28:59][D][climate:404]:   Fan Mode: AUTO
[16:28:59][D][climate:410]:   Preset: NONE
[16:28:59][D][climate:416]:   Swing Mode: OFF
[16:28:59][D][climate:419]:   Current Temperature: 22.80°C
[16:28:59][D][climate:425]:   Target Temperature: 24.00°C
[16:28:59][W][samsung_ac:709]: s:20.00.01 d:b0.00.ff VAR_in_temp_eva_in_f 23
[16:28:59][W][samsung_ac:716]: s:20.00.01 d:b0.00.ff VAR_in_temp_eva_out_f 22.6
[16:29:02][W][samsung_ac:725]: s:10.00.00 d:b0.00.ff VAR_out_error_code 0
[16:29:02][D][sensor:094]: 'error_code': Sending state 0.00000  with 0 decimals of accuracy

### YAML Configuration

```yaml
## BASIC CONFIGURATION
esphome:
  name: samsung-ac
  friendly_name: Climate

# Select chipset and board configuration - in this case M5STACK
esp32:
  board: m5stack-atom

# [Optional] - Create web interface where you can control the AC from your web browser (without Home Assistant)
web_server:
  port: 80

mqtt:
    broker: mosquitto.home

# Enable logging
logger:
  logs:
    component: ERROR # Remove the "Your component takes to long to respond warning"

# Enable native API for communication with Home Assistant, this can be removed if you do not plan to use it with Home Assistant
api:

# Enable OTA firmware update, you will be able to upload the firmware over WiFi without connecting the device by cables
ota:
  platform: esphome

# Setup your WiFi password
wifi:
  ssid: "XXXXX" #
  password: "XXXXXX" #

captive_portal:

# Specify pins used by the board to comunicate with RS485 board - in this case M5STACK
uart:
  tx_pin: GPIO19   # Use GPIO26 for ATOM Tail485
  rx_pin: GPIO22   # Use GPIO32 for ATOM Tail485
  # For older devices it could also be 2400. But you should start with 9600.
  baud_rate: 9600
  parity: EVEN

## SAMSUNG AC CONFIGURATION

# Import custom component from GitHub
external_components:
  - source: github://omerfaruk-aran/esphome_samsung_hvac_bus@main # Use @stable if you want a more stable experience, but note a lot of this example code breaks.
    components: [samsung_ac]

# Configuration of AC component
samsung_ac:
  non_nasa_keepalive: false
  debug_log_undefined_messages: false
  debug_log_messages: true
  capabilities:
    vertical_swing: true
    horizontal_swing: true
    # Presets define special AC modes like Windfree, Eco, and so on.
    # The following modes are available: sleep, quiet, fast, longreach, windfree, eco.
    presets:
      # Short version - a quick and simple way to enable presets.
      quiet: true
      windfree: true
      eco: true
      sleep: true
      fast: true
      # Long version - allows customization, including localized names and control over enabling the presets.
      # fast:
      #   name: "Fast cooling"
      #   enabled: true

  devices:
    # Caroline
    - address: "20.00.00" # Indoor device address
      climate:
        name: "Caroline AC"
      room_temperature:
        name: "Caroline AC temperature"
      target_temperature:
        name: "Caroline AC target temperature"
      power:
        name: "Caroline AC power"
      mode:
        name: "Caroline AC mode"

      #Add automatic_cleaning mode for Samsung AC NASA
            #- Added the "automatic_cleaning" feature to the Samsung AC integration.
            #- This mode ensures hygienic drying of all moisture in the indoor unit after the cooling process is completed.
      automatic_cleaning:
        name: "Caroline AC automatic clean"

      # If your AC sits near or inside the ceiling, the reported room temperature is often a little bit heigher then whats
      # measured below. This property can be used to correct that value.
      #room_temperature_offset: -1.4

      # Only supported on NASA devices
      room_humidity:
        name: "Caroline AC humidity"

    - address: "20.00.01" # Indoor device address
      climate:
        name: "Logeerkamer AC"

    # The controls directly below are all included in the climate control. Its adviced to only add the climate control and skip the extra controls.
      room_temperature:
        name: "Logeerkamer AC temperature"
      target_temperature:
        name: "Logeerkamer AC target temperature"
      power:
        name: "Logeerkamer AC power"
      mode:
        name: "Logeerkamer AC mode"

      #Add automatic_cleaning mode for Samsung AC NASA
            #- Added the "automatic_cleaning" feature to the Samsung AC integration.
            #- This mode ensures hygienic drying of all moisture in the indoor unit after the cooling process is completed.
      automatic_cleaning:
        name: "Logeerkamer AC automatic clean"

      # If your AC sits near or inside the ceiling, the reported room temperature is often a little bit heigher then whats
      # measured below. This property can be used to correct that value.
      #room_temperature_offset: -1.4

      # Only supported on NASA devices
      room_humidity:
        name: "Logeerkamer AC humidity"

    - address: "20.00.02" # Indoor device address
      climate:
        name: "Slaapkamer AC"

    # The controls directly below are all included in the climate control. Its adviced to only add the climate control and skip the extra controls.
      room_temperature:
        name: "Slaapkamer AC temperature"
      target_temperature:
        name: "Slaapkamer AC target temperature"
      power:
        name: "Slaapkamer AC power"
      mode:
        name: "Slaapkamer AC mode"

      #Add automatic_cleaning mode for Samsung AC NASA
            #- Added the "automatic_cleaning" feature to the Samsung AC integration.
            #- This mode ensures hygienic drying of all moisture in the indoor unit after the cooling process is completed.
      automatic_cleaning:
        name: "Slaapkamer AC automatic clean"

      # If your AC sits near or inside the ceiling, the reported room temperature is often a little bit heigher then whats
      # measured below. This property can be used to correct that value.
      #room_temperature_offset: -1.4

      # Only supported on NASA devices
      room_humidity:
        name: "Slaapkamer AC humidity"

    - address: "10.00.00" # Outdoor device address as the following components are dependent on an outdoor unit.
      # This sensor captures and monitors specific error codes returned by the HVAC system.
      # When an error occurs, the sensor detects the error code and updates its value accordingly.
      # Additionally, by using the blueprint available at https://github.com/omerfaruk-aran/esphome_samsung_ac_blueprint,
      # you can automatically send detailed error messages to your mobile devices based on the captured error codes.
      error_code:
        name: error_code

      # This sensor measures the instantaneous power consumption of the outdoor unit in Watts.
      # The captured value represents the current power draw of the outdoor HVAC components, helping track energy usage patterns.
      outdoor_instantaneous_power:
        name: "Outdoor Instantaneous Power"

      # This sensor records the cumulative energy consumption of the outdoor unit in kWh.
      # It calculates the total energy consumed over time, allowing users to monitor and analyze energy efficiency.
      outdoor_cumulative_energy:
        name: "Outdoor Cumulative Energy"

      # This sensor measures the current drawn by the outdoor unit in Amperes.
      # Monitoring current values helps identify electrical irregularities and ensure safe power levels in the system.
      outdoor_current:
        name: "Outdoor Current"

      # This sensor tracks the voltage supplied to the outdoor unit in Volts.
      # Consistent voltage readings indicate stable power delivery, while deviations can help detect electrical issues in the system.
      outdoor_voltage:
        name: "Outdoor Voltage"
```

### Additional Details

Otherwise the integration works perfect, I can read and control my units from Openhab just fine. Only the log file is flooded with these warnings.

Thanks for this very helpfull software!
