### ISSUE TITLE
`Bug` [Samsung_HVAC]: Power went out. My ACs are throwing an error and do not turn on.

### ISSUE THREAD

**Issue by goncalorijo** [omerfaruk-aran/esphome_samsung_hvac_bus#273]
### The problem

Hello,

I have 8 Samsung Internal ACs units and 3 Samsung External units. I also have 3 M5Stack devices that are flashed with this software. I was using during the last years this ESPHome integration flawlessly but during the recent power outage that happened in Europe, our house had no energy during 10 hours.

When power came back, the AC's are throwing an error on their internal display (flashing E2 01).
This error is related with the number or internal units not being correct read.

It was the first time our AC power went out and for some reason it looks like it is not recovering. It seems that our M5Stack devices are influencing the start up counting procedure.

The log is being spammed with these messages:

![Image](https://github.com/user-attachments/assets/8cb8bc3d-5395-466c-8bf9-bd38885d1878)

Is this a known issue?
Can anyone help me on a procedure to have everything up and running?

Thank you!
Gonçalo Rijo

### ESPHome Version

2025.4.0

### Samsung HVAC Component Version

2.0.5

### Home Assistant Version

Home Assistant OS 15.2

### AC Type

OTHER

### Indoor AC Unit Model

Samsung

### Outdoor AC Unit Model

Samsung

### ESP Device Model

m5stack-atom

### Connection Points

F1/F2

### ESPHome Logs

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2025.4.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.13.2",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Lisbon",
    "os_name": "Linux",
    "os_version": "6.12.23-haos",
    "supervisor": "2025.04.1",
    "host_os": "Home Assistant OS 15.2",
    "docker_version": "28.0.4",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "documentation": "https://hacs.xyz/docs/use/",
      "version": "2.0.5",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "frigate": {
      "documentation": "https://github.com/blakeblackshear/frigate",
      "version": "5.8.0",
      "requirements": [
        "hass-web-proxy-lib==0.0.7"
      ]
    }
  },
  "integration_manifest": {
    "domain": "esphome",
    "name": "ESPHome",
    "after_dependencies": [
      "zeroconf",
      "tag"
    ],
    "codeowners": [
      "OttoWinter",
      "jesserockz",
      "kbx81",
      "bdraco"
    ],
    "config_flow": true,
    "dependencies": [
      "assist_pipeline",
      "bluetooth",
      "intent",
      "ffmpeg",
      "http"
    ],
    "dhcp": [
      {
        "registered_devices": true
      }
    ],
    "documentation": "https://www.home-assistant.io/integrations/esphome",
    "integration_type": "device",
    "iot_class": "local_push",
    "loggers": [
      "aioesphomeapi",
      "noiseprotocol",
      "bleak_esphome"
    ],
    "mqtt": [
      "esphome/discover/#"
    ],
    "requirements": [
      "aioesphomeapi==29.9.0",
      "esphome-dashboard-api==1.2.3",
      "bleak-esphome==2.12.0"
    ],
    "zeroconf": [
      "_esphomelib._tcp.local."
    ],
    "is_built_in": true,
    "overwrites_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 0.007670091000001378
    },
    "01J4MEW86WY8R5K2CD36APAW70": {
      "wait_import_platforms": -1.415882626000002,
      "config_entry_setup": 1.4208395299999985
    },
    "01J4MEWJ6FQ8ZT0N6X4TWNEB1T": {
      "wait_import_platforms": -1.4195701860000014,
      "config_entry_setup": 1.4239135000000012
    },
    "01J4BHZXC9F3QV6N4SQTBB0NJ3": {
      "wait_import_platforms": -1.4209617540000004,
      "config_entry_setup": 1.4274936360000012
    }
  },
  "data": {
    "config": {
      "created_at": "1970-01-01T00:00:00+00:00",
      "data": {
        "device_name": "ac-m5stack-quartoescadas",
        "host": "192.168.1.140",
        "noise_psk": "",
        "password": "",
        "port": 6053
      },
      "discovery_keys": {
        "dhcp": [
          {
            "__type": "<class 'homeassistant.helpers.discovery_flow.DiscoveryKey'>",
            "repr": "DiscoveryKey(domain='dhcp', key='e86bea305a58', version=1)"
          }
        ],
        "zeroconf": [
          {
            "__type": "<class 'homeassistant.helpers.discovery_flow.DiscoveryKey'>",
            "repr": "DiscoveryKey(domain='zeroconf', key=('_esphomelib._tcp.local.', 'ac-m5stack-quartoescadas._esphomelib._tcp.local.'), version=1)"
          }
        ]
      },
      "disabled_by": null,
      "domain": "esphome",
      "entry_id": "01J4MEWJ6FQ8ZT0N6X4TWNEB1T",
      "minor_version": 1,
      "modified_at": "2024-10-07T10:53:20.810368+00:00",
      "options": {
        "allow_service_calls": false
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "zeroconf",
      "subentries": [],
      "title": "Controlador AC M5Stack Quarto Escadas",
      "unique_id": "e8:6b:ea:30:5a:58",
      "version": 1
    },
    "storage_data": {
      "device_info": {
        "uses_password": false,
        "name": "ac-m5stack-quartoescadas",
        "friendly_name": "Controlador AC M5Stack Quarto Escadas",
        "mac_address": "**REDACTED**",
        "compilation_time": "Apr 29 2025, 00:00:54",
        "model": "m5stack-atom",
        "manufacturer": "Espressif",
        "has_deep_sleep": false,
        "esphome_version": "2025.4.0",
        "project_name": "",
        "project_version": "",
        "webserver_port": 80,
        "legacy_voice_assistant_version": 0,
        "voice_assistant_feature_flags": 0,
        "legacy_bluetooth_proxy_version": 0,
        "bluetooth_proxy_feature_flags": 0,
        "suggested_area": "",
        "bluetooth_mac_address": ""
      },
      "services": [],
      "api_version": {
        "major": 1,
        "minor": 10
      },
      "update": [],
      "climate": [
        {
          "object_id": "piso_1_-_quarto_escadas",
          "key": 3123100496,
          "name": "Piso 1 - Quarto Escadas",
          "unique_id": "ac-m5stack-quartoescadasclimatepiso_1_-_quarto_escadas",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "supports_current_temperature": true,
          "supports_two_point_target_temperature": false,
          "supported_modes": [
            0,
            2,
            3,
            4,
            5,
            6
          ],
          "visual_min_temperature": 16.0,
          "visual_max_temperature": 30.0,
          "visual_target_temperature_step": 1.0,
          "visual_current_temperature_step": 1.0,
          "legacy_supports_away": false,
          "supports_action": false,
          "supported_fan_modes": [
            2,
            3,
            5,
            6
          ],
          "supported_swing_modes": [],
          "supported_custom_fan_modes": [
            "Turbo"
          ],
          "supported_presets": [],
          "supported_custom_presets": [],
          "supports_current_humidity": false,
          "supports_target_humidity": false,
          "visual_min_humidity": 30.0,
          "visual_max_humidity": 99.0
        },
        {
          "object_id": "piso_1_-_quarto_terraco",
          "key": 1787511728,
          "name": "Piso 1 - Quarto Terraco",
          "unique_id": "ac-m5stack-quartoescadasclimatepiso_1_-_quarto_terraco",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "supports_current_temperature": true,
          "supports_two_point_target_temperature": false,
          "supported_modes": [
            0,
            2,
            3,
            4,
            5,
            6
          ],
          "visual_min_temperature": 16.0,
          "visual_max_temperature": 30.0,
          "visual_target_temperature_step": 1.0,
          "visual_current_temperature_step": 1.0,
          "legacy_supports_away": false,
          "supports_action": false,
          "supported_fan_modes": [
            2,
            3,
            5,
            6
          ],
          "supported_swing_modes": [],
          "supported_custom_fan_modes": [
            "Turbo"
          ],
          "supported_presets": [],
          "supported_custom_presets": [],
          "supports_current_humidity": false,
          "supports_target_humidity": false,
          "visual_min_humidity": 30.0,
          "visual_max_humidity": 99.0
        },
        {
          "object_id": "piso_1_-_closet",
          "key": 1810613729,
          "name": "Piso 1 - Closet",
          "unique_id": "ac-m5stack-quartoescadasclimatepiso_1_-_closet",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "supports_current_temperature": true,
          "supports_two_point_target_temperature": false,
          "supported_modes": [
            0,
            2,
            3,
            4,
            5,
            6
          ],
          "visual_min_temperature": 16.0,
          "visual_max_temperature": 30.0,
          "visual_target_temperature_step": 1.0,
          "visual_current_temperature_step": 1.0,
          "legacy_supports_away": false,
          "supports_action": false,
          "supported_fan_modes": [
            2,
            3,
            5,
            6
          ],
          "supported_swing_modes": [],
          "supported_custom_fan_modes": [
            "Turbo"
          ],
          "supported_presets": [],
          "supported_custom_presets": [],
          "supports_current_humidity": false,
          "supports_target_humidity": false,
          "visual_min_humidity": 30.0,
          "visual_max_humidity": 99.0
        }
      ]
    },
    "dashboard": "5c53de3b_esphome"
  }
}

### Samsung AC Logs

[12:13:41][W][samsung_ac:091]: write 32d0c8d1d2000000000000001b34
[12:13:41][W][samsung_ac:091]: write 32d0c8d1d2000000000000001b34
[12:13:41][W][samsung_ac:091]: write 32d0c8d1d2000000000000001b34
[12:13:41][W][samsung_ac:091]: write 32d0c8d1d2000000000000001b34
[12:13:41][W][samsung_ac:091]: write 32d0c8d1d2000000000000001b34
[12:13:41][W][samsung_ac:091]: write 32d0c8d1d2000000000000001b34
[12:13:41][W][samsung_ac:091]: write 32d0c8d1d2000000000000001b34
[12:13:41][W][samsung_ac:091]: write 32d0c8d1d2000000000000001b34
[12:13:42][W][samsung_ac:104]: Last transmission too long ago. Reset RX index.
[12:13:42][W][samsung_ac:091]: write 32d0c8d1d2000000000000001b34
[12:13:42][W][samsung_ac:091]: write 32d0c8d1d2000000000000001b34
[12:13:42][W][samsung_ac:091]: write 32d0c8d1d2000000000000001b34
[12:13:42][W][samsung_ac:091]: write 32d0c8d1d2000000000000001b34
[12:13:42][W][samsung_ac:091]: write 32d0c8d1d2000000000000001b34
[12:13:42][W][samsung_ac:091]: write 32d0c8d1d2000000000000001b34
[12:13:42][W][samsung_ac:091]: write 32d0c8d1d2000000000000001b34
[12:13:42][W][samsung_ac:091]: write 32d0c8d1d2000000000000001b34
[12:13:42][W][samsung_ac:091]: write 32d0c8d1d2000000000000001b34
[12:13:42][W][samsung_ac:091]: write 32d0c8d1d2000000000000001b34
[12:13:42][W][samsung_ac:091]: write 32d0c8d1d2000000000000001b34
[12:13:42][W][samsung_ac:091]: write 32d0c8d1d2000000000000001b34
[12:13:42][W][samsung_ac:091]: write 32d0c8d1d2000000000000001b34
[12:13:42][W][samsung_ac:091]: write 32d0c8d1d2000000000000001b34
[12:13:42][W][samsung_ac:091]: write 32d0c8d1d2000000000000001b34
[12:13:43][W][samsung_ac:091]: write 32d0c8d1d2000000000000001b34
[12:13:43][W][samsung_ac:091]: write 32d0c8d1d2000000000000001b34

### YAML Configuration

```yaml
# This example provides a basic configuration and description based on the M5STACK components
# For further configuration you should visit the ESPHome docs https://esphome.io
# Every line starting with a # can be removed.

## BASIC CONFIGURATION
esphome:
  name: ac-m5stack-quartoescadas
  friendly_name: Controlador AC M5Stack Quarto Escadas

# Select chipset and board configuration - in this case M5STACK
esp32:
  board: m5stack-atom

# [Optional] - Create web interface where you can control the AC from your web browser (without Home Assistant)
web_server:
  port: 80

# Enable logging
logger:
  level: INFO
  logs:
    component: ERROR # Remove the "Your component takes to long to respond warning"

# Enable native API for communication with Home Assistant, this can be removed if you do not plan to use it with Home Assistant
api:

# Enable OTA firmware update, you will be able to upload the firmware over WiFi without connecting the device by cables
ota:
  platform: esphome
# Setup your WiFi password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

# Specify pins used by the board to comunicate with RS485 board - in this case M5STACK
uart:
  tx_pin: GPIO26   # Use GPIO26 for ATOM Tail485 
  rx_pin: GPIO32   # Use GPIO32 for ATOM Tail485
  # For older devices it could also be 2400. But you should start with 9600.
  baud_rate: 9600
  parity: EVEN

## SAMSUNG AC CONFIGURATION

# Import custom component from GitHub
external_components:
  - source: github://lanwin/esphome_samsung_ac@main # use @main if you want the latest development (possibly unstable?)
    components: [samsung_ac]

# Configuration of AC component
samsung_ac:

  # For NonNASA devices the following option can be enabled to prevent the device from sleeping when idle. This allows
  # values like internal and external temperature to continue to be tracked when the device isn't in use.
  non_nasa_keepalive: true

  # Capabilities configure the features alle devices of your AC system have (all parts of this section are optional). 
  # All capabilities are off by default, you need to enable only those your devices have.
  # You can override or configure them also on a per devices basis (look below for that).
  capabilities: 
    vertical_swing: false
#    horizontal_swing: true
    # Presets define special AC modes like Windfree and so on. 
    # The following modes are available: sleep, quiet, fast, longreach, windfree
#    presets: 
      # short version
      #quiet: true
      # long version - allows to locilize names
#      quiet:
#        name: "Makes no sound"
#        enabled: true

  
  devices:
    # Skip everything below on the first run! Wait a minute, watch your ESPHome logs until you see the "Discovered devices:" section and you see some addresses:
    # For NASA devices it looks like this (with 4 indoor devices): 
    #   Indoor:  20.00.00, 20.00.01, 20.00.02, 20.00.03
    # For NonNASA devices it looks like this (with 2 indoor devices): 
    #   Indoor:  00, 01
    # You need this addresses for the the sections below. If you see only a "-" then you should visit the troubleshooting section in the readme. 



    # Repeat everything below for each indoor device address you see in your logs


    - address: "00" # Indoor device address 
      # Each property below is optional (climate, room_temperature etc.) - you can delete those which you dont need.
      # For the names we suggest to choose a combination of room name and the thing it controls. 

      # Configures/overrides the capabilites for this devices. 
      # Look above for all options.
#      capabilities:
#        horizontal_swing: false # This device have no h swing. 

      # Creates climate control in Home Assistant. A climate control combines multiple of the controls below (like temperature, mode etc.)
      climate:
        name: "Piso 1 - Quarto Escadas"

      # The controls directly below are all included in the climate control. Its adviced to only add the climate control and skip the extra controls.
#      room_temperature:
#        name: "Temperatura Actual"
#      target_temperature:
#        name: "Temperatura Desejada"
#      power:
#        name: "Power"
#      mode:
#        name: "Mode"




    - address: "01" # Indoor device address 
      # Each property below is optional (climate, room_temperature etc.) - you can delete those which you dont need.
      # For the names we suggest to choose a combination of room name and the thing it controls. 

      # Configures/overrides the capabilites for this devices. 
      # Look above for all options.
#      capabilities:
#        horizontal_swing: false # This device have no h swing. 

      # Creates climate control in Home Assistant. A climate control combines multiple of the controls below (like temperature, mode etc.)
      climate:
        name: "Piso 1 - Quarto Terraco"

      # The controls directly below are all included in the climate control. Its adviced to only add the climate control and skip the extra controls.
#      room_temperature:
#        name: "Temperatura Actual"
#      target_temperature:
#        name: "Temperatura Desejada"
#      power:
#        name: "Power"
#      mode:
#        name: "Mode"




    - address: "02" # Indoor device address 
      # Each property below is optional (climate, room_temperature etc.) - you can delete those which you dont need.
      # For the names we suggest to choose a combination of room name and the thing it controls. 

      # Configures/overrides the capabilites for this devices. 
      # Look above for all options.
#      capabilities:
#        horizontal_swing: false # This device have no h swing. 

      # Creates climate control in Home Assistant. A climate control combines multiple of the controls below (like temperature, mode etc.)
      climate:
        name: "Piso 1 - Closet"

      # The controls directly below are all included in the climate control. Its adviced to only add the climate control and skip the extra controls.
#      room_temperature:
#        name: "Temperatura Actual"
#      target_temperature:
#        name: "Temperatura Desejada"
#      power:
#        name: "Power"
#      mode:
#        name: "Mode"
```
