### ISSUE TITLE
`Bug` [Samsung_HVAC]: Example.yaml not being able to compile

### ISSUE THREAD

**Issue by Sh4r0** [omerfaruk-aran/esphome_samsung_hvac_bus#274]
### The problem

The example.yaml configuration gives the following error: 

module 'esphome.components.sensor' has no attribute '_UNDEF'

### ESPHome Version

2025.5.0

### Samsung HVAC Component Version

20240213.1

### Home Assistant Version

2025.5.2

### AC Type

NASA

### Indoor AC Unit Model

Doesn't matter

### Outdoor AC Unit Model

Doesn't matter

### ESP Device Model

M5STACK ATOM LITE + M5STACK RS-485

### Connection Points

Doesn't matter

### ESPHome Logs

module 'esphome.components.sensor' has no attribute '_UNDEF'

### YAML Configuration

```yaml
## BASIC CONFIGURATION
esphome:
  name: samsung_ac
  friendly_name: Climate

# Select chipset and board configuration - in this case M5STACK
esp32:
  board: m5stack-atom

# [Optional] - Create web interface where you can control the AC from your web browser (without Home Assistant)
web_server:
  port: 80

# Enable logging
logger:
  logs:
    component: ERROR # Remove the "Your component takes too long to respond warning"

# Enable native API for communication with Home Assistant, this can be removed if you do not plan to use it with Home Assistant
api:

# Enable OTA firmware update, you will be able to upload the firmware over WiFi without connecting the device by cables
ota:
  platform: esphome

# Setup your WiFi password
wifi:
  ssid: "My WiFi Name" # !!!CHANGE ME!!!
  password: "My WiFi Password" # !!!CHANGE ME!!!

captive_portal:

# Specify pins used by the board to comunicate with RS485 board - in this case M5STACK
uart:
  tx_pin: GPIO19    # Use GPIO26 for ATOM Tail485 
  rx_pin: GPIO22    # Use GPIO32 for ATOM Tail485
  # For older devices it could also be 2400. But you should start with 9600.
  baud_rate: 9600
  parity: EVEN

## SAMSUNG AC CONFIGURATION

# Import custom component from GitHub
external_components:
  - source: github://omerfaruk-aran/esphome_samsung_hvac_bus@main
    components: [samsung_ac]

# Configuration of AC component
samsung_ac:

  # For NonNASA devices the following option can be enabled to prevent the device from sleeping when idle. This allows
  # values like internal and external temperature to continue to be tracked when the device isn't in use.
  non_nasa_keepalive: true
  
  # When enabled (set to true), this option will log the messages associated with undefined codes on the device. This is useful for debugging and identifying any unexpected or unknown codes that the device may receive during operation.
  debug_log_undefined_messages: false
  
  # When enabled (set to true), this option logs messages associated with defined codes on the device. This helps in monitoring the behavior of the device by recording the activity related to known, expected codes.
  debug_log_messages: false

  # Capabilities configure the features that all devices of your AC system have (all parts of this section are optional). 
  # All capabilities are off by default, you need to enable only those your devices have.
  # You can override or configure them also on a per-device basis (look below for that).
  capabilities: 
    vertical_swing: true
    horizontal_swing: true
    # Presets define special AC modes like Windfree, Eco, and so on. 
    # The following modes are available: sleep, quiet, fast, longreach, windfree, eco.
    presets: 
      # Short version - a quick and simple way to enable presets.
      quiet: true
      # Long version - allows customization, including localized names and control over enabling the presets.
      fast:
        name: "Fast cooling"
        enabled: true

  devices:
    # Skip everything below on the first run! Wait a minute, watch your ESPHome logs until you see the "Discovered devices:" section and you see some addresses:
    # For NASA devices it looks like this (with 1 outdoor device and 4 indoor devices): 
    #   Outdoor: 10.00.00
    #   Indoor:  20.00.00, 20.00.01, 20.00.02, 20.00.03
    # For NonNASA devices it looks like this (with 2 indoor devices): 
    #   Indoor:  00, 01
    # You need these addresses for the the sections below. If you see only a "-" then you should visit the troubleshooting section in the readme. 

    # Repeat everything below for each indoor device address you see in your logs
    - address: "20.00.00" # Indoor device address 
      # Each property below is optional (climate, room_temperature etc.) - you can delete those which you dont need.
      # For the names we suggest to choose a combination of room name and the thing it controls. 

      # Configures/overrides the capabilites for this devices. 
      # Look above for all options.
      capabilities:
        horizontal_swing: false # This device have no h swing. 

      # Creates climate control in Home Assistant. A climate control combines multiple of the controls below (like temperature, mode etc.)
      climate:
        name: "Kitchen climate"

      # The controls directly below are all included in the climate control. Its advised to only add the climate control and skip the extra controls.
      room_temperature:
        name: "Kitchen temperature"
      target_temperature:
        name: "Kitchen target temperature"
      power:
        name: "Kitchen power"
      mode:
        name: "Kitchen mode"

      #Add automatic_cleaning mode for Samsung AC NASA
      automatic_cleaning:
        name: "Kitchen automatic clean"

      # If your AC sits near or inside the ceiling, the reported room temperature is often a little bit higher than what's 
      # measured below. This property can be used to correct that value.
      room_temperature_offset: -1.4

      # Only supported on NASA devices
      # This sensor was problematic due to _UNDEF in the custom component's Python code.
      # room_humidity:
      #   name: "Kitchen humidity"
      
    - address: "10.00.00" # Outdoor device address as the following components are dependent on an outdoor unit.
      # This sensor was problematic due to _UNDEF in the custom component's Python code.
      # error_code:
      #   name: error_code
        
      # This sensor measures the instantaneous power consumption of the outdoor unit in Watts.
      # The captured value represents the current power draw of the outdoor HVAC components, helping track energy usage patterns.
      outdoor_instantaneous_power:
        name: "Outdoor Instantaneous Power"

      # This sensor records the cumulative energy consumption of the outdoor unit in kWh.
      # It calculates the total energy consumed over time, allowing users to monitor and analyze energy efficiency.
      outdoor_cumulative_energy:
        name: "Outdoor Cumulative Energy"

      # These sensors were problematic due to _UNDEF in the custom component's Python code.
      # outdoor_current:
      #   name: "Outdoor Current"

      # outdoor_voltage:
      #   name: "Outdoor Voltage"

      # Only supported on NASA based heatpumps
      # This sensor was problematic due to _UNDEF in the custom component's Python code.
      # water_temperature:
      #   name: "Warm water"
      water_target_temperature:
        name: "Hot Water Target Temperature"
      water_heater_mode:
        name: "Hotwater Mode"
      outdoor_temperature: # Should be used with outdoor device address
        name: "Outdoor temperature"
```

**Comment by arundalep** [comment]
I'm having the same issue since updating ESP Home.

**Comment by Madanbot** [comment]
Hi and thanks for your great work!

After updating to ESPHome 2025.5.0, the samsung_ac component fails to compile due to usage of `sensor._UNDEF`, which no longer exists in the current ESPHome codebase.

**Error:**

**Comment by dierkgrossfeld** [comment]
According to https://esphome.io/changelog/2025.5.0.html and more specific https://github.com/esphome/esphome/pull/8725

the _UNDEF

should be replaced by cv.UNDEFINED

After that replacement it compiles at least without errors.....

**Comment by dierkgrossfeld** [comment]
so I replaced in the  __init__.py:
```unit_of_measurement: str = sensor._UNDEF,
icon: str = sensor._UNDEF,
accuracy_decimals: int = sensor._UNDEF,
device_class: str = sensor._UNDEF,
state_class: str = sensor._UNDEF,
entity_category: str = sensor._UNDEF,
```

by

```unit_of_measurement: str = sensor.cv.UNDEFINED,
icon: str = sensor.cv.UNDEFINED,
accuracy_decimals: int = sensor.cv.UNDEFINED,
device_class: str = sensor.cv.UNDEFINED,
state_class: str = sensor.cv.UNDEFINED,
entity_category: str = sensor.cv.UNDEFINED,
```

**Comment by smartminjos** [comment]
> so I replaced in the **init**.py:
> 
> ```
> icon: str = sensor._UNDEF,
> accuracy_decimals: int = sensor._UNDEF,
> device_class: str = sensor._UNDEF,
> state_class: str = sensor._UNDEF,
> entity_category: str = sensor._UNDEF,
> ```
> 
> by
> 
> ```
> icon: str = sensor.cv.UNDEFINED,
> accuracy_decimals: int = sensor.cv.UNDEFINED,
> device_class: str = sensor.cv.UNDEFINED,
> state_class: str = sensor.cv.UNDEFINED,
> entity_category: str = sensor.cv.UNDEFINED,
> ```

Sorry, could you please indicate where init.py file is stored ? many thanks

**Comment by dierkgrossfeld** [comment]
Its this one:

https://github.com/omerfaruk-aran/esphome_samsung_hvac_bus/blob/main/components/samsung_ac/__init__.py

**Comment by dierkgrossfeld** [comment]
Hmm, it worked flawlessly up to esphome 2024.4.2 for me. Maybe there is something else wrong ?
Wheres your build failing ?

**Comment by smartminjos** [comment]
> Hmm, it worked flawlessly up to esphome 2024.4.2 for me. Maybe there is something else wrong ? Wheres your build failing ?

well actually it worked until 2025.5.2 too for me. 

No i wonder how to move from UNDEF to cv.UNDEFINED ..... since init.py here is still old and not changed. I do no how to make the change by myselve? to 

![Image](https://github.com/user-attachments/assets/14250429-9160-46e6-9914-37053f5e2802)

**Comment by dierkgrossfeld** [comment]
I personally did that on the esphome instance itself.
There is a hidden .esphome folder with external_components in it.
So edited simply that file there.

**Comment by dierkgrossfeld** [comment]
The thing is:
I am not very well at python and dont understand the depth that change has and what else it may affect.
Thats why I dont make that change and do a PR.....

**Comment by smartminjos** [comment]
i am lost even more i guess :)))) do not see than folder, donno what to do :)))))

**Comment by dudu15051505** [comment]
Same error.

ESPHome Version

2025.5.0
Samsung HVAC Component Version

20240213.1
Home Assistant Version

2025.5.2

AC Type

NASA

ESP Device Model

M5STACK ATOM LITE + M5STACK RS-485

ESPHome Logs

module 'esphome.components.sensor' has no attribute '_UNDEF'

````

# This example provides a basic configuration and description based on the M5STACK components
# For further configuration you should visit the ESPHome docs https://esphome.io
# Every line starting with a # can be removed.

## BASIC CONFIGURATION
esphome:
  name: asdfasdfsdfT
  friendly_name: asdfasdfsdfT

# Select chipset and board configuration - in this case M5STACK
esp32:
  board: m5stack-atom

# [Optional] - Create web interface where you can control the AC from your web browser (without Home Assistant)
web_server:
  port: 80

# Enable logging
logger:
  logs:
    component: ERROR # Remove the "Your component takes to long to respond warning"

# Enable native API for communication with Home Assistant, this can be removed if you do not plan to use it with Home Assistant
api:
  encryption:
    key: "asdfasdfsdfTasdfasdfsdfTasdfasdfsdfTasdfasdfsdfTasdfasdfsdfT"

# Enable OTA firmware update, you will be able to upload the firmware over WiFi without connecting the device by cables
ota:
  - platform: esphome
    password: "asdfasdfsdfT"

# Setup your WiFi password
wifi:
  ssid: "asdfasdfsdfT" # !!!CHANGE ME!!!
  password: "asdfasdfsdfT" # !!!CHANGE ME!!!
  
  ap:
    ssid: "asdfasdfsdfT"
    password: "asdfasdfsdfT"

captive_portal:

# Specify pins used by the board to comunicate with RS485 board - in this case M5STACK
uart:
  tx_pin: GPIO19   # Use GPIO26 for ATOM Tail485 
  rx_pin: GPIO22   # Use GPIO32 for ATOM Tail485
  # For older devices it could also be 2400. But you should start with 9600.
  baud_rate: 9600
  parity: EVEN

## SAMSUNG AC CONFIGURATION

# Import custom component from GitHub
external_components:
  - source: github://omerfaruk-aran/esphome_samsung_hvac_bus@main # Use @stable if you want a more stable experience, but note a lot of this example code breaks.
    components: [samsung_ac]

# Configuration of AC component
samsung_ac:

  # For NonNASA devices the following option can be enabled to prevent the device from sleeping when idle. This allows
  # values like internal and external temperature to continue to be tracked when the device isn't in use.
  non_nasa_keepalive: true
  
  # When enabled (set to true), this option will log the messages associated with undefined codes on the device. This is useful for debugging and identifying any unexpected or unknown codes that the device may receive during operation.
  debug_log_undefined_messages: false
  
  # When enabled (set to true), this option logs messages associated with defined codes on the device. This helps in monitoring the behavior of the device by recording the activity related to known, expected codes.
  debug_log_messages: false

  # Capabilities configure the features that all devices of your AC system have (all parts of this section are optional). 
  # All capabilities are off by default, you need to enable only those your devices have.
  # You can override or configure them also on a per-device basis (look below for that).
  capabilities: 
    vertical_swing: true
    horizontal_swing: true
    # Presets define special AC modes like Windfree, Eco, and so on. 
    # The following modes are available: sleep, quiet, fast, longreach, windfree, eco.
    presets: 
      # Short version - a quick and simple way to enable presets.
      quiet: true
      sleep: true
      windfree: true
      eco: true
      # Long version - allows customization, including localized names and control over enabling the presets.
      fast:
        name: "Fast cooling"
        enabled: true

  devices:
    # Skip everything below on the first run! Wait a minute, watch your ESPHome logs until you see the "Discovered devices:" section and you see some addresses:
    # For NASA devices it looks like this (with 1 outdoor device and 4 indoor devices): 
    #   Outdoor: 10.00.00
    #   Indoor:  20.00.00, 20.00.01, 20.00.02, 20.00.03
    # For NonNASA devices it looks like this (with 2 indoor devices): 
    #   Indoor:  00, 01
    # You need these addresses for the the sections below. If you see only a "-" then you should visit the troubleshooting section in the readme. 

    # Repeat everything below for each indoor device address you see in your logs
    - address: "20.00.00" # Indoor device address 
      # Each property below is optional (climate, room_temperature etc.) - you can delete those which you dont need.
      # For the names we suggest to choose a combination of room name and the thing it controls. 

      # Configures/overrides the capabilites for this devices. 
      # Look above for all options.
      capabilities: 
        vertical_swing: true
        horizontal_swing: true
        # Presets define special AC modes like Windfree, Eco, and so on. 
        # The following modes are available: sleep, quiet, fast, longreach, windfree, eco.
        presets: 
          # Short version - a quick and simple way to enable presets.
          quiet:
            name: "Silencioso"
            enabled: true
          sleep:
            name: "Dormir"
            enabled: true
          windfree:
            name: "Windfree"
            enabled: true
          eco:
            name: "Economico"
            enabled: true
          fast:
            name: "Turbo"
            enabled: true

      # Creates climate control in Home Assistant. A climate control combines multiple of the controls below (like temperature, mode etc.)
      climate:
        name: "Gustavo quarto climate"

      # The controls directly below are all included in the climate control. Its adviced to only add the climate control and skip the extra controls.
      room_temperature:
        name: "Gustavo quarto temperature"
      target_temperature:
        name: "Gustavo quarto target temperature"
      power:
        name: "Gustavo quarto power"
      mode:
        name: "Gustavo quarto mode"

      #Add automatic_cleaning mode for Samsung AC NASA
            #- Added the "automatic_cleaning" feature to the Samsung AC integration.
            #- This mode ensures hygienic drying of all moisture in the indoor unit after the cooling process is completed.
      automatic_cleaning:
        name: "Gustavo quarto automatic clean"

      # If your AC sits near or inside the ceiling, the reported room temperature is often a little bit heigher then whats 
      # measured below. This property can be used to correct that value.
      #room_temperature_offset: -1.4
      room_temperature_offset: 0

      # Only supported on NASA devices
      room_humidity:
        name: "Gustavo quarto humidity"
      
    - address: "10.00.00" # Outdoor device address as the following components are dependent on an outdoor unit.
      # This sensor captures and monitors specific error codes returned by the HVAC system.
      # When an error occurs, the sensor detects the error code and updates its value accordingly.
      # Additionally, by using the blueprint available at https://github.com/omerfaruk-aran/esphome_samsung_ac_blueprint,
      # you can automatically send detailed error messages to your mobile devices based on the captured error codes.
      error_code:
        name: error_code
        
      # This sensor measures the instantaneous power consumption of the outdoor unit in Watts.
      # The captured value represents the current power draw of the outdoor HVAC components, helping track energy usage patterns.
      outdoor_instantaneous_power:
        name: "Outdoor Instantaneous Power"

      # This sensor records the cumulative energy consumption of the outdoor unit in kWh.
      # It calculates the total energy consumed over time, allowing users to monitor and analyze energy efficiency.
      outdoor_cumulative_energy:
        name: "Outdoor Cumulative Energy"

      # This sensor measures the current drawn by the outdoor unit in Amperes.
      # Monitoring current values helps identify electrical irregularities and ensure safe power levels in the system.
      outdoor_current:
        name: "Outdoor Current"

      # This sensor tracks the voltage supplied to the outdoor unit in Volts.
      # Consistent voltage readings indicate stable power delivery, while deviations can help detect electrical issues in the system.
      outdoor_voltage:
        name: "Outdoor Voltage"

      # Only supported on NASA based heatpumps
      outdoor_temperature: # Should be used with outdoor device address
        name: "Outdoor temperature"

````

````

INFO ESPHome 2025.5.0
INFO Reading configuration /config/esphome/asdfasdfsdfT.yaml...
ERROR Unexpected exception while reading configuration:
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/esphome/esphome/__main__.py", line 1083, in main
    return run_esphome(sys.argv)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 1061, in run_esphome
    config = read_config(dict(args.substitution) if args.substitution else {})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config.py", line 1095, in read_config
    res = load_config(command_line_substitutions)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config.py", line 949, in load_config
    return _load_config(command_line_substitutions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config.py", line 939, in _load_config
    return validate_config(config, command_line_substitutions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config.py", line 835, in validate_config
    target_platform = core_config.preload_core_config(config, result)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/core/config.py", line 233, in preload_core_config
    if _is_target_platform(domain):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/core/config.py", line 194, in _is_target_platform
    return get_component(name, True).is_target_platform
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/loader.py", line 209, in get_component
    return _lookup_module(domain, exception)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/loader.py", line 185, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/data/external_components/22448af3/components/samsung_ac/__init__.py", line 146, in <module>
    unit_of_measurement: str = sensor._UNDEF,
                               ^^^^^^^^^^^^^
AttributeError: module 'esphome.components.sensor' has no attribute '_UNDEF'

````
