### ISSUE TITLE
`Bug` [Samsung_HVAC]: home assistant 2025.6.0 update, "Entity no longer has a state class" for humidity sensor

### ISSUE THREAD

**Issue by dudu15051505** [omerfaruk-aran/esphome_samsung_hvac_bus#285]
### The problem

After updating Home Assistant 2025.6.0, Home Assistant itself is indicating that the humidity sensor created by Samsung HVAC Bus is no longer supported due to lack of state class.

### ESPHome Version

2025.5.2

### Samsung HVAC Component Version

20240213.1, more accurate Commit 2584a90

### Home Assistant Version

2025.6.0

### AC Type

NASA

### Indoor AC Unit Model

AR18CVFAAWKNAZ

### Outdoor AC Unit Model

AR18CVFAAWKXAZ

### ESP Device Model

M5STACK ATOM LITE + M5STACK RS-485

### Connection Points

F1/F2

### ESPHome Logs

```json
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2025.6.0",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.13.3",
    "docker": true,
    "arch": "x86_64",
    "timezone": "America/Sao_Paulo",
    "os_name": "Linux",
    "os_version": "6.12.23-haos",
    "supervisor": "2025.05.3",
    "host_os": "Home Assistant OS 15.2",
    "docker_version": "28.0.4",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "documentation": "https://hacs.xyz/docs/use/",
      "version": "2.0.5",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "tuya_local": {
      "documentation": "https://github.com/make-all/tuya-local",
      "version": "2025.6.0",
      "requirements": [
        "tinytuya==1.17.1",
        "tuya-device-sharing-sdk~=0.2.1"
      ]
    },
    "hoymiles_wifi": {
      "documentation": "https://github.com/suaveolent/ha-hoymiles-wifi",
      "version": "0.3.5",
      "requirements": [
        "hoymiles-wifi==0.3.4"
      ]
    }
  },
  "integration_manifest": {
    "domain": "esphome",
    "name": "ESPHome",
    "after_dependencies": [
      "hassio",
      "zeroconf",
      "tag"
    ],
    "codeowners": [
      "OttoWinter",
      "jesserockz",
      "kbx81",
      "bdraco"
    ],
    "config_flow": true,
    "dependencies": [
      "assist_pipeline",
      "bluetooth",
      "intent",
      "ffmpeg",
      "http"
    ],
    "dhcp": [
      {
        "registered_devices": true
      }
    ],
    "documentation": "https://www.home-assistant.io/integrations/esphome",
    "integration_type": "device",
    "iot_class": "local_push",
    "loggers": [
      "aioesphomeapi",
      "noiseprotocol",
      "bleak_esphome"
    ],
    "mqtt": [
      "esphome/discover/#"
    ],
    "quality_scale": "platinum",
    "requirements": [
      "aioesphomeapi==32.2.1",
      "esphome-dashboard-api==1.3.0",
      "bleak-esphome==2.16.0"
    ],
    "zeroconf": [
      "_esphomelib._tcp.local."
    ],
    "is_built_in": true,
    "overwrites_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 0.011935451067984104
    },
    "01JPDKS49S6B09SARSW0WHKCXG": {
      "wait_import_platforms": -1.0390255670063198,
      "wait_base_component": -0.0014666479546576738,
      "config_entry_setup": 1.0562432219740003
    },
    "01JPDAJKQZM8GSDFSCPCK4QCSG": {
      "wait_import_platforms": -1.0426740900147706,
      "config_entry_setup": 1.0628403750015423
    }
  },
  "data": {
    "config": {
      "created_at": "2025-03-15T19:16:32.697823+00:00",
      "data": {
        "device_name": "samsung-ac-escritorio",
        "host": "172.16.2.61",
        "noise_psk": "**REDACTED**",
        "password": "",
        "port": 6053
      },
      "discovery_keys": {
        "dhcp": [
          {
            "__type": "<class 'homeassistant.helpers.discovery_flow.DiscoveryKey'>",
            "repr": "DiscoveryKey(domain='dhcp', key='901506fa71ac', version=1)"
          }
        ],
        "zeroconf": [
          {
            "__type": "<class 'homeassistant.helpers.discovery_flow.DiscoveryKey'>",
            "repr": "DiscoveryKey(domain='zeroconf', key=('_esphomelib._tcp.local.', 'samsung-ac-escritorio._esphomelib._tcp.local.'), version=1)"
          }
        ]
      },
      "disabled_by": null,
      "domain": "esphome",
      "entry_id": "01JPDKS49S6B09SARSW0WHKCXG",
      "minor_version": 1,
      "modified_at": "2025-03-21T23:18:48.011379+00:00",
      "options": {
        "allow_service_calls": false
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "subentries": [],
      "title": "AC_Escritorio_ESP",
      "unique_id": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "version": 1
    },
    "storage_data": {
      "device_info": {
        "uses_password": false,
        "name": "samsung-ac-escritorio",
        "friendly_name": "AC_Escritorio_ESP",
        "mac_address": "**REDACTED**",
        "compilation_time": "Jun  3 2025, 07:25:01",
        "model": "m5stack-atom",
        "manufacturer": "Espressif",
        "has_deep_sleep": false,
        "esphome_version": "2025.5.2",
        "project_name": "",
        "project_version": "",
        "webserver_port": 80,
        "legacy_voice_assistant_version": 0,
        "voice_assistant_feature_flags": 0,
        "legacy_bluetooth_proxy_version": 0,
        "bluetooth_proxy_feature_flags": 0,
        "suggested_area": "",
        "bluetooth_mac_address": ""
      },
      "services": [],
      "api_version": {
        "major": 1,
        "minor": 10
      },
      "update": [],
      "switch": [
        {
          "object_id": "escritorio_power",
          "key": 1330409052,
          "name": "Escritorio power",
          "unique_id": "samsung-ac-escritorioswitchescritorio_power",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "assumed_state": false,
          "device_class": ""
        },
        {
          "object_id": "escritorio_automatic_clean",
          "key": 1647827912,
          "name": "Escritorio automatic clean",
          "unique_id": "samsung-ac-escritorioswitchescritorio_automatic_clean",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "assumed_state": false,
          "device_class": ""
        }
      ],
      "climate": [
        {
          "object_id": "escritorio_climate",
          "key": 4034895790,
          "name": "Escritorio climate",
          "unique_id": "samsung-ac-escritorioclimateescritorio_climate",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "supports_current_temperature": true,
          "supports_two_point_target_temperature": false,
          "supported_modes": [
            0,
            2,
            3,
            4,
            5,
            6
          ],
          "visual_min_temperature": 16.0,
          "visual_max_temperature": 30.0,
          "visual_target_temperature_step": 1.0,
          "visual_current_temperature_step": 1.0,
          "legacy_supports_away": false,
          "supports_action": false,
          "supported_fan_modes": [
            2,
            3,
            5,
            6
          ],
          "supported_swing_modes": [
            0,
            1,
            2,
            3
          ],
          "supported_custom_fan_modes": [
            "Turbo"
          ],
          "supported_presets": [
            0
          ],
          "supported_custom_presets": [
            "Dormir",
            "Economico",
            "Silencioso",
            "Turbo",
            "Windfree"
          ],
          "supports_current_humidity": false,
          "supports_target_humidity": false,
          "visual_min_humidity": 30.0,
          "visual_max_humidity": 99.0
        }
      ],
      "sensor": [
        {
          "object_id": "escritorio_temperature",
          "key": 2903452341,
          "name": "Escritorio temperature",
          "unique_id": "samsung-ac-escritoriosensorescritorio_temperature",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "temperature",
          "unit_of_measurement": "\u00b0C",
          "accuracy_decimals": 1,
          "force_update": false,
          "state_class": 1,
          "legacy_last_reset_type": 0
        },
        {
          "object_id": "escritorio_humidity",
          "key": 2860231850,
          "name": "Escritorio humidity",
          "unique_id": "samsung-ac-escritoriosensorescritorio_humidity",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "",
          "unit_of_measurement": "",
          "accuracy_decimals": 0,
          "force_update": false,
          "state_class": 0,
          "legacy_last_reset_type": 0
        },
        {
          "object_id": "outdoor_temperature",
          "key": 2033033012,
          "name": "Outdoor temperature",
          "unique_id": "samsung-ac-escritoriosensoroutdoor_temperature",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "temperature",
          "unit_of_measurement": "\u00b0C",
          "accuracy_decimals": 1,
          "force_update": false,
          "state_class": 1,
          "legacy_last_reset_type": 0
        },
        {
          "object_id": "error_code",
          "key": 374491335,
          "name": "error_code",
          "unique_id": "samsung-ac-escritoriosensorerror_code",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "device_class": "",
          "unit_of_measurement": "",
          "accuracy_decimals": 0,
          "force_update": false,
          "state_class": 0,
          "legacy_last_reset_type": 0
        },
        {
          "object_id": "outdoor_instantaneous_power",
          "key": 1605503050,
          "name": "Outdoor Instantaneous Power",
          "unique_id": "samsung-ac-escritoriosensoroutdoor_instantaneous_power",
          "disabled_by_default": false,
          "icon": "mdi:flash",
          "entity_category": 0,
          "device_class": "power",
          "unit_of_measurement": "W",
          "accuracy_decimals": 1,
          "force_update": false,
          "state_class": 1,
          "legacy_last_reset_type": 0
        },
        {
          "object_id": "outdoor_cumulative_energy",
          "key": 1495752774,
          "name": "Outdoor Cumulative Energy",
          "unique_id": "samsung-ac-escritoriosensoroutdoor_cumulative_energy",
          "disabled_by_default": false,
          "icon": "mdi:counter",
          "entity_category": 0,
          "device_class": "energy",
          "unit_of_measurement": "kWh",
          "accuracy_decimals": 3,
          "force_update": false,
          "state_class": 2,
          "legacy_last_reset_type": 0
        },
        {
          "object_id": "outdoor_current",
          "key": 998158885,
          "name": "Outdoor Current",
          "unique_id": "samsung-ac-escritoriosensoroutdoor_current",
          "disabled_by_default": false,
          "icon": "mdi:current-ac",
          "entity_category": 0,
          "device_class": "current",
          "unit_of_measurement": "A",
          "accuracy_decimals": 2,
          "force_update": false,
          "state_class": 1,
          "legacy_last_reset_type": 0
        },
        {
          "object_id": "outdoor_voltage",
          "key": 164489076,
          "name": "Outdoor Voltage",
          "unique_id": "samsung-ac-escritoriosensoroutdoor_voltage",
          "disabled_by_default": false,
          "icon": "mdi:flash",
          "entity_category": 0,
          "device_class": "voltage",
          "unit_of_measurement": "V",
          "accuracy_decimals": 1,
          "force_update": false,
          "state_class": 1,
          "legacy_last_reset_type": 0
        }
      ],
      "text_sensor": [],
      "number": [
        {
          "object_id": "escritorio_target_temperature",
          "key": 3067084701,
          "name": "Escritorio target temperature",
          "unique_id": "samsung-ac-escritorionumberescritorio_target_temperature",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "min_value": 16.0,
          "max_value": 30.0,
          "step": 1.0,
          "unit_of_measurement": "\u00b0C",
          "mode": 0,
          "device_class": "temperature"
        }
      ],
      "select": [
        {
          "object_id": "escritorio_mode",
          "key": 4235062276,
          "name": "Escritorio mode",
          "unique_id": "samsung-ac-escritorioselectescritorio_mode",
          "disabled_by_default": false,
          "icon": "",
          "entity_category": 0,
          "options": [
            "Auto",
            "Cool",
            "Dry",
            "Fan",
            "Heat"
          ]
        }
      ]
    },
    "dashboard": {
      "configured": true,
      "supports_update": true,
      "last_update_success": true,
      "last_exception": null,
      "addon": "5c53de3b_esphome",
      "has_matching_name": true,
      "device": {
        "configuration": "ac-escritorio-esp.yaml",
        "current_version": "2025.5.2",
        "deployed_version": "2025.5.2",
        "loaded_integrations": [
          "api",
          "async_tcp",
          "captive_portal",
          "climate",
          "esp32",
          "esphome",
          "external_components",
          "json",
          "logger",
          "md5",
          "mdns",
          "network",
          "number",
          "ota",
          "preferences",
          "safe_mode",
          "samsung_ac",
          "select",
          "sensor",
          "socket",
          "switch",
          "uart",
          "web_server",
          "web_server_base",
          "wifi"
        ],
        "target_platform": "ESP32"
      }
    }
  }
}
```
### Samsung AC Logs

INFO ESPHome 2025.5.2
INFO Reading configuration /config/esphome/ac-escritorio-esp.yaml...
INFO Starting log output from 172.16.2.61 using esphome API
INFO Successfully connected to samsung-ac-escritorio @ 172.16.2.61 in 0.096s
INFO Successful handshake with samsung-ac-escritorio @ 172.16.2.61 in 0.099s
[10:45:08][I][app:115]: ESPHome version 2025.5.2 compiled on Jun  3 2025, 07:25:01
[10:45:08][C][wifi:600]: WiFi:
[10:45:08][C][wifi:428]:   Local MAC: [redacted]
[10:45:08][C][wifi:433]:   SSID: [redacted]
[10:45:08][C][wifi:436]:   IP Address: 172.16.2.61
[10:45:08][C][wifi:440]:   BSSID: [redacted]
[10:45:08][C][wifi:441]:   Hostname: 'samsung-ac-escritorio'
[10:45:08][C][wifi:443]:   Signal strength: -49 dB ▂▄▆█
[10:45:08][C][wifi:447]:   Channel: 6
[10:45:08][C][wifi:448]:   Subnet: 255.255.255.0
[10:45:08][C][wifi:449]:   Gateway: 172.16.2.1
[10:45:08][C][wifi:450]:   DNS1: 172.16.2.1
[10:45:08][C][wifi:451]:   DNS2: 0.0.0.0
[10:45:08][C][logger:224]: Logger:
[10:45:08][C][logger:225]:   Max Level: DEBUG
[10:45:08][C][logger:226]:   Initial Level: DEBUG
[10:45:08][C][logger:228]:   Log Baud Rate: 115200
[10:45:08][C][logger:229]:   Hardware UART: UART0
[10:45:08][C][logger:233]:   Task Log Buffer Size: 768
[10:45:08][C][logger:238]:   Level for 'component': ERROR
[10:45:08][C][uart.arduino_esp32:151]: UART Bus 1:
[10:45:08][C][uart.arduino_esp32:152]:   TX Pin: GPIO19
[10:45:08][C][uart.arduino_esp32:153]:   RX Pin: GPIO22
[10:45:08][C][uart.arduino_esp32:155]:   RX Buffer Size: 256
[10:45:08][C][uart.arduino_esp32:157]:   Baud Rate: 9600 baud
[10:45:08][C][uart.arduino_esp32:158]:   Data Bits: 8
[10:45:08][C][uart.arduino_esp32:159]:   Parity: EVEN
[10:45:08][C][uart.arduino_esp32:160]:   Stop bits: 1
[10:45:08][C][captive_portal:089]: Captive Portal:
[10:45:08][C][web_server:285]: Web Server:
[10:45:08][C][web_server:286]:   Address: samsung-ac-escritorio.local:80
[10:45:08][C][mdns:120]: mDNS:
[10:45:08][C][mdns:121]:   Hostname: samsung-ac-escritorio
[10:45:08][C][esphome.ota:073]: Over-The-Air updates:
[10:45:08][C][esphome.ota:074]:   Address: samsung-ac-escritorio.local:3232
[10:45:08][C][esphome.ota:075]:   Version: 2
[10:45:08][C][esphome.ota:078]:   Password configured
[10:45:08][C][safe_mode:018]: Safe Mode:
[10:45:08][C][safe_mode:020]:   Boot considered successful after 60 seconds
[10:45:08][C][safe_mode:021]:   Invoke after 10 boot attempts
[10:45:08][C][safe_mode:023]:   Remain in safe mode for 300 seconds
[10:45:08][C][api:170]: API Server:
[10:45:08][C][api:171]:   Address: samsung-ac-escritorio.local:6053
[10:45:08][C][api:173]:   Using noise encryption: YES
[10:45:10][D][sensor:094]: 'Outdoor temperature': Sending state 17.50000 °C with 1 decimals of accuracy
[10:45:10][D][sensor:094]: 'Outdoor Current': Sending state 0.00000 A with 2 decimals of accuracy
[10:45:10][D][sensor:094]: 'error_code': Sending state 0.00000  with 0 decimals of accuracy
[10:45:11][D][sensor:094]: 'error_code': Sending state 0.00000  with 0 decimals of accuracy
[10:45:14][D][sensor:094]: 'error_code': Sending state 0.00000  with 0 decimals of accuracy
[10:45:16][D][sensor:094]: 'Escritorio temperature': Sending state 18.70000 °C with 1 decimals of accuracy
[10:45:16][D][climate:396]: 'Escritorio climate' - Sending state:
[10:45:16][D][climate:399]:   Mode: OFF
[10:45:16][D][climate:407]:   Custom Fan Mode: Turbo
[10:45:16][D][climate:410]:   Preset: NONE
[10:45:16][D][climate:416]:   Swing Mode: BOTH
[10:45:16][D][climate:419]:   Current Temperature: 18.70°C
[10:45:16][D][climate:425]:   Target Temperature: 24.00°C
[10:45:17][D][sensor:094]: 'error_code': Sending state 0.00000  with 0 decimals of accuracy
[10:45:20][D][sensor:094]: 'error_code': Sending state 0.00000  with 0 decimals of accuracy
[10:45:21][D][sensor:094]: 'Outdoor temperature': Sending state 17.50000 °C with 1 decimals of accuracy
[10:45:21][D][sensor:094]: 'Outdoor Current': Sending state 0.00000 A with 2 decimals of accuracy
[10:45:21][D][sensor:094]: 'error_code': Sending state 0.00000  with 0 decimals of accuracy
[10:45:23][D][sensor:094]: 'error_code': Sending state 0.00000  with 0 decimals of accuracy
[10:45:23][D][device_state_tracker:046]: No change in value for device: 20.00.00
[10:45:23][C][samsung_ac:053]: Configured devices: 10.00.00, 20.00.00
[10:45:23][C][samsung_ac:065]: Discovered devices:
[10:45:23][C][samsung_ac:066]:   Outdoor: 10.00.00
[10:45:23][C][samsung_ac:067]:   Indoor:  20.00.00
[10:45:26][D][sensor:094]: 'error_code': Sending state 0.00000  with 0 decimals of accuracy
[10:45:26][D][sensor:094]: 'Escritorio temperature': Sending state 18.70000 °C with 1 decimals of accuracy
[10:45:26][D][climate:396]: 'Escritorio climate' - Sending state:
[10:45:26][D][climate:399]:   Mode: OFF
[10:45:26][D][climate:407]:   Custom Fan Mode: Turbo
[10:45:26][D][climate:410]:   Preset: NONE
[10:45:26][D][climate:416]:   Swing Mode: BOTH
[10:45:26][D][climate:419]:   Current Temperature: 18.70°C
[10:45:26][D][climate:425]:   Target Temperature: 24.00°C
[10:45:29][D][sensor:094]: 'error_code': Sending state 0.00000  with 0 decimals of accuracy
[10:45:32][D][sensor:094]: 'Outdoor Voltage': Sending state 211.00000 V with 1 decimals of accuracy
[10:45:32][D][sensor:094]: 'Outdoor temperature': Sending state 17.50000 °C with 1 decimals of accuracy
[10:45:32][D][sensor:094]: 'Outdoor Current': Sending state 0.00000 A with 2 decimals of accuracy
[10:45:32][D][sensor:094]: 'error_code': Sending state 0.00000  with 0 decimals of accuracy
[10:45:32][D][sensor:094]: 'Outdoor Instantaneous Power': Sending state 0.00000 W with 1 decimals of accuracy
[10:45:32][D][sensor:094]: 'Outdoor Cumulative Energy': Sending state 67.27500 kWh with 3 decimals of accuracy
[10:45:33][D][sensor:094]: 'error_code': Sending state 0.00000  with 0 decimals of accuracy
[10:45:36][D][sensor:094]: 'error_code': Sending state 0.00000  with 0 decimals of accuracy
[10:45:36][D][sensor:094]: 'Escritorio temperature': Sending state 18.70000 °C with 1 decimals of accuracy
[10:45:36][D][climate:396]: 'Escritorio climate' - Sending state:
[10:45:36][D][climate:399]:   Mode: OFF
[10:45:36][D][climate:407]:   Custom Fan Mode: Turbo
[10:45:36][D][climate:410]:   Preset: NONE
[10:45:36][D][climate:416]:   Swing Mode: BOTH
[10:45:36][D][climate:419]:   Current Temperature: 18.70°C
[10:45:36][D][climate:425]:   Target Temperature: 24.00°C
### YAML Configuration

```yaml
# This example provides a basic configuration and description based on the M5STACK components
# For further configuration you should visit the ESPHome docs https://esphome.io
# Every line starting with a # can be removed.

## BASIC CONFIGURATION
esphome:
  name: samsung-ac-escritorio
  friendly_name: AC_Escritorio_ESP

# Select chipset and board configuration - in this case M5STACK
esp32:
  board: m5stack-atom

# [Optional] - Create web interface where you can control the AC from your web browser (without Home Assistant)
web_server:
  port: 80

# Enable logging
logger:
  logs:
    component: ERROR # Remove the "Your component takes to long to respond warning"

# Enable native API for communication with Home Assistant, this can be removed if you do not plan to use it with Home Assistant
api:
  encryption:
    key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Enable OTA firmware update, you will be able to upload the firmware over WiFi without connecting the device by cables
ota:
  - platform: esphome
    password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Setup your WiFi password
wifi:
  ssid: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" # !!!CHANGE ME!!!
  password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" # !!!CHANGE ME!!!
  
  ap:
    ssid: "Ac-Samsung-Escritorio"
    password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

captive_portal:

# Specify pins used by the board to comunicate with RS485 board - in this case M5STACK
uart:
  tx_pin: GPIO19   # Use GPIO26 for ATOM Tail485 
  rx_pin: GPIO22   # Use GPIO32 for ATOM Tail485
  # For older devices it could also be 2400. But you should start with 9600.
  baud_rate: 9600
  parity: EVEN

## SAMSUNG AC CONFIGURATION

# Import custom component from GitHub
external_components:
  - source: github://omerfaruk-aran/esphome_samsung_hvac_bus@main # Use @stable if you want a more stable experience, but note a lot of this example code breaks.
    components: [samsung_ac]

# Configuration of AC component
samsung_ac:

  # For NonNASA devices the following option can be enabled to prevent the device from sleeping when idle. This allows
  # values like internal and external temperature to continue to be tracked when the device isn't in use.
  non_nasa_keepalive: true
  
  # When enabled (set to true), this option will log the messages associated with undefined codes on the device. This is useful for debugging and identifying any unexpected or unknown codes that the device may receive during operation.
  debug_log_undefined_messages: false
  
  # When enabled (set to true), this option logs messages associated with defined codes on the device. This helps in monitoring the behavior of the device by recording the activity related to known, expected codes.
  debug_log_messages: false

  # Capabilities configure the features that all devices of your AC system have (all parts of this section are optional). 
  # All capabilities are off by default, you need to enable only those your devices have.
  # You can override or configure them also on a per-device basis (look below for that).
  capabilities: 
    vertical_swing: true
    horizontal_swing: true
    # Presets define special AC modes like Windfree, Eco, and so on. 
    # The following modes are available: sleep, quiet, fast, longreach, windfree, eco.
    presets: 
      # Short version - a quick and simple way to enable presets.
      quiet: true
      sleep: true
      windfree: true
      eco: true
      # Long version - allows customization, including localized names and control over enabling the presets.
      fast:
        name: "Fast cooling"
        enabled: true

  devices:
    # Skip everything below on the first run! Wait a minute, watch your ESPHome logs until you see the "Discovered devices:" section and you see some addresses:
    # For NASA devices it looks like this (with 1 outdoor device and 4 indoor devices): 
    #   Outdoor: 10.00.00
    #   Indoor:  20.00.00, 20.00.01, 20.00.02, 20.00.03
    # For NonNASA devices it looks like this (with 2 indoor devices): 
    #   Indoor:  00, 01
    # You need these addresses for the the sections below. If you see only a "-" then you should visit the troubleshooting section in the readme. 

    # Repeat everything below for each indoor device address you see in your logs
    - address: "20.00.00" # Indoor device address 
      # Each property below is optional (climate, room_temperature etc.) - you can delete those which you dont need.
      # For the names we suggest to choose a combination of room name and the thing it controls. 

      # Configures/overrides the capabilites for this devices. 
      # Look above for all options.
      capabilities: 
        vertical_swing: true
        horizontal_swing: true
        # Presets define special AC modes like Windfree, Eco, and so on. 
        # The following modes are available: sleep, quiet, fast, longreach, windfree, eco.
        presets: 
          # Short version - a quick and simple way to enable presets.
          quiet:
            name: "Silencioso"
            enabled: true
          sleep:
            name: "Dormir"
            enabled: true
          windfree:
            name: "Windfree"
            enabled: true
          eco:
            name: "Economico"
            enabled: true
          fast:
            name: "Turbo"
            enabled: true

      # Creates climate control in Home Assistant. A climate control combines multiple of the controls below (like temperature, mode etc.)
      climate:
        name: "Escritorio climate"

      # The controls directly below are all included in the climate control. Its adviced to only add the climate control and skip the extra controls.
      room_temperature:
        name: "Escritorio temperature"
      target_temperature:
        name: "Escritorio target temperature"
      power:
        name: "Escritorio power"
      mode:
        name: "Escritorio mode"

      #Add automatic_cleaning mode for Samsung AC NASA
            #- Added the "automatic_cleaning" feature to the Samsung AC integration.
            #- This mode ensures hygienic drying of all moisture in the indoor unit after the cooling process is completed.
      automatic_cleaning:
        name: "Escritorio automatic clean"

      # If your AC sits near or inside the ceiling, the reported room temperature is often a little bit heigher then whats 
      # measured below. This property can be used to correct that value.
      #room_temperature_offset: -1.4
      room_temperature_offset: 0

      # Only supported on NASA devices
      room_humidity:
        name: "Escritorio humidity"
      
    - address: "10.00.00" # Outdoor device address as the following components are dependent on an outdoor unit.
      # This sensor captures and monitors specific error codes returned by the HVAC system.
      # When an error occurs, the sensor detects the error code and updates its value accordingly.
      # Additionally, by using the blueprint available at https://github.com/omerfaruk-aran/esphome_samsung_ac_blueprint,
      # you can automatically send detailed error messages to your mobile devices based on the captured error codes.
      error_code:
        name: error_code
        
      # This sensor measures the instantaneous power consumption of the outdoor unit in Watts.
      # The captured value represents the current power draw of the outdoor HVAC components, helping track energy usage patterns.
      outdoor_instantaneous_power:
        name: "Outdoor Instantaneous Power"

      # This sensor records the cumulative energy consumption of the outdoor unit in kWh.
      # It calculates the total energy consumed over time, allowing users to monitor and analyze energy efficiency.
      outdoor_cumulative_energy:
        name: "Outdoor Cumulative Energy"

      # This sensor measures the current drawn by the outdoor unit in Amperes.
      # Monitoring current values helps identify electrical irregularities and ensure safe power levels in the system.
      outdoor_current:
        name: "Outdoor Current"

      # This sensor tracks the voltage supplied to the outdoor unit in Volts.
      # Consistent voltage readings indicate stable power delivery, while deviations can help detect electrical issues in the system.
      outdoor_voltage:
        name: "Outdoor Voltage"

      # Only supported on NASA based heatpumps
      outdoor_temperature: # Should be used with outdoor device address
        name: "Outdoor temperature"
```

### Additional Details

https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics
![Image](https://github.com/user-attachments/assets/c979c19b-9273-4520-a252-500b5aadc8f0)
text on the image:

The entity no longer has a state class

We have generated statistics for ' AC_Escritorio_ESP Escritorio humidity ' ( sensor.samsung_ac_escritorio_escritorio_humidity ) in the past, but it no longer has a state class, so we can no longer track long-term statistics for it.

Statistics cannot be generated until this entity has a compatible state class.

If the state class was previously provided by an integration, this may be a bug. Please report an issue.

If you previously defined the state class yourself, please fix it. The different state classes and when to use them can be found in the developer documentation.

If the state class has been permanently removed, you may want to delete its long-term statistics from your database.

Do you want to permanently delete the long-term statistics for sensor.samsung_ac_escritorio_escritorio_humidity from your database?

----------------
sensor history:
![Image](https://github.com/user-attachments/assets/5004533c-3dde-4104-be01-a1ad3964378f)
![Image](https://github.com/user-attachments/assets/8c2bc238-a043-4cac-82d3-333c27c0ae22)
